export function getMerchantTicketCopy(locale: string) {
  if (locale === "fr") {
    return {
      back: "Retour",
      backToStore: "Boutique",
      backToTickets: "Billets",
      backToTicket: "Billet",
      checkIn: "Contrôler un billet",
      checkInHint: "Scanner le QR ou saisir le code",
      empty: "Aucun billet lié à cette boutique pour le moment.",
      emptyHint: "Un administrateur peut associer un billet à votre boutique.",
      history: "Historique des contrôles",
      historyEmpty: "Aucun billet contrôlé pour le moment.",
      historyHint: "Chaque contrôle confirmé apparaît ici.",
      historyCount: (count: number) => `${count} contrôles`,
      invited: "Invitation envoyée",
      issued: "Attribués",
      invite: "Inviter",
      inviteError: "Impossible d'envoyer l'invitation. Vérifiez le code Friemi.",
      inviteAlreadyActive: "Cette personne peut déjà contrôler ce billet.",
      inviteAlreadyPending: "Une invitation attend déjà sa réponse.",
      inviteNotFound: "Aucun compte ne correspond à ce code Friemi.",
      inviteSelf: "Vous avez déjà accès à ce billet.",
      inviteLabel: "Code Friemi de la personne",
      invitePlaceholder: "Code à 6 chiffres",
      inviteTitle: "Inviter une personne au contrôle",
      inviteHint: "Cette personne pourra contrôler ce billet, sans recevoir de stock.",
      managedTickets: "Billets de la boutique",
      methodCode: "Code saisi",
      methodQr: "QR scanné",
      methodUnknown: "Méthode non enregistrée",
      next: "Suivant",
      page: (page: number, total: number) => `${page} / ${total}`,
      pending: "Invitation en attente",
      previous: "Précédent",
      redeemed: "Contrôlés",
      redeemedBy: (name: string) => `Contrôlé par ${name}`,
      redeemFor: (name: string) => `Billet de ${name}`,
      remove: "Retirer l'accès",
      removeConfirm: "Confirmer le retrait",
      removeError: "Impossible de retirer cet accès.",
      removeHint: "Cette personne ne pourra plus contrôler ce billet. L'historique reste disponible.",
      removeCancel: "Annuler",
      removed: "Accès retiré",
      staff: "Personnel de contrôle",
      activeStaff: "Personnel actif",
      staffList: "Accès en cours",
      manager: "Responsable",
      staffEmpty: "Aucune personne invitée pour ce billet.",
      staffHint: "L'accès est limité à ce billet.",
      statusActive: "Actif",
      statusPending: "En attente",
      statusRevoked: "Retiré",
      supply: "Billets créés",
      tickets: "Billets d'événement",
      ticketsHint: "Choisissez un billet pour gérer son contrôle.",
      ticketTypeCount: (count: number) => `${count} types`,
      viewTicket: "Gérer ce billet",
    };
  }

  if (locale === "en") {
    return {
      back: "Back",
      backToStore: "Store",
      backToTickets: "Tickets",
      backToTicket: "Ticket",
      checkIn: "Check in a ticket",
      checkInHint: "Scan the QR or enter the code",
      empty: "No tickets are linked to this store yet.",
      emptyHint: "A site administrator can link a ticket to your store.",
      history: "Check-in history",
      historyEmpty: "No tickets have been checked in yet.",
      historyHint: "Every confirmed check-in appears here.",
      historyCount: (count: number) => `${count} check-ins`,
      invited: "Invitation sent",
      issued: "Allocated",
      invite: "Invite",
      inviteError: "Could not send the invitation. Check the Friemi code.",
      inviteAlreadyActive: "This person can already check in this ticket.",
      inviteAlreadyPending: "An invitation is already awaiting a response.",
      inviteNotFound: "No account matches this Friemi code.",
      inviteSelf: "You already have access to this ticket.",
      inviteLabel: "Staff member's Friemi code",
      invitePlaceholder: "6-digit code",
      inviteTitle: "Invite check-in staff",
      inviteHint: "They can check in this ticket without receiving ticket stock.",
      managedTickets: "Store tickets",
      methodCode: "Entered code",
      methodQr: "Scanned QR",
      methodUnknown: "Method not recorded",
      next: "Next",
      page: (page: number, total: number) => `${page} / ${total}`,
      pending: "Invitation pending",
      previous: "Previous",
      redeemed: "Checked in",
      redeemedBy: (name: string) => `Checked in by ${name}`,
      redeemFor: (name: string) => `Ticket held by ${name}`,
      remove: "Remove access",
      removeConfirm: "Confirm removal",
      removeError: "Could not remove this access.",
      removeHint: "They will no longer be able to check in this ticket. The history remains.",
      removeCancel: "Cancel",
      removed: "Access removed",
      staff: "Check-in staff",
      activeStaff: "Active staff",
      staffList: "Current access",
      manager: "Manager",
      staffEmpty: "No staff invited for this ticket yet.",
      staffHint: "Access applies only to this ticket.",
      statusActive: "Active",
      statusPending: "Pending",
      statusRevoked: "Removed",
      supply: "Tickets created",
      tickets: "Event tickets",
      ticketsHint: "Choose a ticket to manage check-in.",
      ticketTypeCount: (count: number) => `${count} types`,
      viewTicket: "Manage this ticket",
    };
  }

  return {
    back: "返回",
    backToStore: "门店",
    backToTickets: "票券列表",
    backToTicket: "票券详情",
    checkIn: "核销票券",
    checkInHint: "扫码或输入核销码",
    empty: "门店暂时没有关联票券",
    emptyHint: "网站管理员绑定票券后，会显示在这里。",
    history: "核销记录",
    historyEmpty: "还没有核销记录",
    historyHint: "每次确认核销后，都会在这里留下一条记录。",
    historyCount: (count: number) => `共 ${count} 条`,
    invited: "邀请已发送",
    issued: "已分发",
    invite: "发送邀请",
    inviteError: "邀请失败，请检查 Friemi 码后重试。",
    inviteAlreadyActive: "此人已能核销这类票。",
    inviteAlreadyPending: "邀请已发送，正在等待对方接受。",
    inviteNotFound: "没有找到这个 Friemi 码对应的账户。",
    inviteSelf: "你已拥有这类票的管理权限。",
    inviteLabel: "核销员的 Friemi 码",
    invitePlaceholder: "输入 6 位 Friemi 码",
    inviteTitle: "邀请核销员",
    inviteHint: "受邀者只获得这类票的核销权限，不会收到票券库存。",
    managedTickets: "门店票券",
    methodCode: "输入核销码",
    methodQr: "扫描二维码",
    methodUnknown: "方式未记录",
    next: "下一页",
    page: (page: number, total: number) => `${page} / ${total}`,
    pending: "待接受邀请",
    previous: "上一页",
    redeemed: "已核销",
    redeemedBy: (name: string) => `核销员：${name}`,
    redeemFor: (name: string) => `持票人：${name}`,
    remove: "撤销权限",
    removeConfirm: "确认撤销",
    removeError: "撤销失败，请稍后重试。",
    removeHint: "撤销后此人不能继续核销这类票，已有记录会保留。",
    removeCancel: "取消",
    removed: "权限已撤销",
    staff: "核销人员",
    activeStaff: "已授权人员",
    staffList: "已邀请人员",
    manager: "负责人",
    staffEmpty: "还没有邀请核销员",
    staffHint: "权限只对当前票种生效。",
    statusActive: "已授权",
    statusPending: "待接受",
    statusRevoked: "已撤销",
    supply: "票券总量",
    tickets: "活动票券",
    ticketsHint: "选择票种，管理核销与人员。",
    ticketTypeCount: (count: number) => `${count} 类票`,
    viewTicket: "管理此票券",
  };
}
