-- Five playful 50-word packs per locale; new rooms choose randomly among active packs.
INSERT INTO "public"."DrawGuessWordBank" ("id", "locale", "category", "title", "description", "words", "sortOrder")
SELECT id, locale, category, title, description, string_to_array(words, '|'), sort_order
FROM (VALUES
  ('pet-chaos-zh', 'zh-CN', '萌宠', '毛孩子营业中', '小动物的迷惑行为，画出来更可爱。', '猫咪钻纸箱|狗狗叼拖鞋|仓鼠跑轮|兔子啃萝卜|柯基追尾巴|猫咪踩键盘|小狗洗澡|小猫照镜子|鹦鹉学说话|乌龟赛跑|金鱼吐泡泡|松鼠藏松果|狗狗玩飞盘|猫咪追光点|刺猬打滚|兔子跳高|小猪泡泥澡|小鸭排队|企鹅滑冰|水獭抱石头|长颈鹿戴围巾|河马刷牙|熊猫爬树|大象喷水|狐狸偷葡萄|狮子打哈欠|猴子摘香蕉|浣熊洗苹果|海豹顶球|羊驼吐口水|蜜蜂采花|蝴蝶停鼻尖|小马甩尾巴|小熊吃蜂蜜|蜗牛搬家|青蛙撑荷叶|螃蟹横着走|章鱼打招呼|鲸鱼喷泉|海豚跳圈|猫咪睡键盘|狗狗戴墨镜|仓鼠藏食物|兔子躲帽子|小羊跳栅栏|火烈鸟单脚站|鹦鹉戴耳机|乌鸦叼硬币|小鸡啄米|海龟晒太阳', 10),
  ('pet-chaos-en', 'en', 'Pets', 'Pet Antics', 'Cute animals up to their funniest tricks.', 'cat in a box|dog with a slipper|hamster on a wheel|rabbit with carrot|corgi chasing tail|cat on a keyboard|dog taking a bath|cat in a mirror|talking parrot|racing turtles|bubbling goldfish|squirrel with acorn|dog with frisbee|cat chasing light|rolling hedgehog|jumping rabbit|pig in a mud bath|ducks in a line|skating penguin|otter with a rock|giraffe in a scarf|hippo brushing teeth|panda climbing tree|elephant spraying|fox with grapes|yawning lion|monkey with banana|raccoon with apple|seal with a ball|spitting llama|bee on a flower|butterfly on a nose|pony swishing tail|bear eating honey|snail moving house|frog under a leaf|sideways crab|waving octopus|whale fountain|dolphin jumping hoop|cat asleep on keys|dog in sunglasses|hamster hiding food|rabbit under a hat|sheep jumping fence|one legged flamingo|parrot with headset|crow with a coin|chick pecking grain|sunbathing turtle', 10),
  ('pet-chaos-fr', 'fr', 'Animaux', 'Bêtises de bêtes', 'Des animaux drôles et adorables à dessiner.', 'chat dans une boîte|chien et pantoufle|hamster dans sa roue|lapin et carotte|corgi suit sa queue|chat sur clavier|bain du chien|chat dans le miroir|perroquet bavard|tortues en course|poisson et bulles|écureuil et gland|chien au frisbee|chat suit la lumière|hérisson roulé|lapin qui saute|cochon dans la boue|canards en file|manchot patineur|loutre et caillou|girafe en écharpe|hippo se brosse|panda dans arbre|éléphant arrose|renard et raisins|lion qui baille|singe et banane|raton lave un fruit|phoque avec ballon|lama qui crache|abeille sur fleur|papillon sur nez|poney agite queue|ours mange du miel|escargot déménage|grenouille au lotus|crabe de côté|pieuvre fait coucou|baleine fontaine|dauphin dans cerceau|chat dort au clavier|chien en lunettes|hamster et graines|lapin sous chapeau|mouton saute clôture|flamant à une patte|perroquet au casque|corbeau et pièce|poussin picore|tortue au soleil', 10),
  ('party-zh', 'zh-CN', '派对', '派对大作战', '生日、舞会和欢闹时刻。', '生日蛋糕|许愿蜡烛|彩色气球|礼物堆|派对帽|拉花彩带|纸屑雨|气球拱门|惊喜礼盒|吹蜡烛|切蛋糕|拆礼物|合照|自拍杆|拍立得|跳舞|迪斯科球|舞台灯|麦克风|卡拉OK|吉他弹唱|架子鼓|小号|钢琴|唱片机|耳机派对|荧光棒|泡泡机|烟花|仙女棒|彩纸炮|桌游夜|骰子|扑克牌|藏宝游戏|套圈|击鼓传花|蒙眼猜人|枕头大战|水球大战|沙滩排球|野餐篮|烧烤架|爆米花桶|棉花糖|冰淇淋车|果汁吧|奶茶杯|甜甜圈塔|派对合影', 11),
  ('party-en', 'en', 'Party', 'Party Time', 'Birthdays, dancing, and playful surprises.', 'birthday cake|wish candle|bright balloons|pile of gifts|party hat|streamers|confetti shower|balloon arch|surprise box|blowing candles|cutting cake|opening a gift|group photo|selfie stick|instant camera|dancing|disco ball|stage lights|microphone|karaoke|guitar song|drum kit|trumpet|piano|record player|silent disco|glow sticks|bubble machine|fireworks|sparklers|confetti popper|board game night|dice|playing cards|treasure hunt|ring toss|passing the parcel|blindfold game|pillow fight|water balloon fight|beach volleyball|picnic basket|barbecue grill|popcorn bucket|marshmallow|ice cream truck|juice bar|bubble tea|donut tower|party photo', 11),
  ('party-fr', 'fr', 'Fête', 'On fait la fête', 'Anniversaires, danse et surprises rigolotes.', 'gâteau anniversaire|bougie de voeu|ballons colorés|pile de cadeaux|chapeau de fête|guirlandes|pluie de confettis|arche de ballons|boîte surprise|souffler bougies|couper le gâteau|ouvrir un cadeau|photo de groupe|perche à selfie|photo instantanée|danse|boule à facettes|lumières de scène|microphone|karaoké|chanson guitare|batterie|trompette|piano|tourne disque|disco au casque|bâtons lumineux|machine à bulles|feu artifice|cierges magiques|canon à confettis|soirée jeux|dés|cartes à jouer|chasse au trésor|jeu des anneaux|cadeau tournant|jeu yeux bandés|bataille oreillers|ballons à eau|volley sur plage|panier pique nique|barbecue|seau de popcorn|guimauve|camion de glaces|bar à jus|thé aux perles|tour de beignets|photo de fête', 11),
  ('mystery-zh', 'zh-CN', '侦探', '小小侦探社', '线索藏好了，来画一场迷你谜案。', '放大镜|指纹|脚印|神秘纸条|密信|藏宝图|旧钥匙|上锁的箱子|密码锁|密码本|手电筒|望远镜|监控摄像头|侦探帽|风衣|黑色墨镜|伪装胡子|秘密通道|暗门|地板机关|墙上地图|线索板|红色绳线|丢失的项链|遗落的手套|破碎花瓶|空相框|窗边梯子|泥巴鞋印|滴水雨伞|夜晚灯塔|神秘脚步|追踪小狗|屋顶黑影|树后人影|门缝信封|神秘包裹|藏宝箱|金色硬币|古老卷轴|钟楼|迷宫|旋转书架|地下室|阁楼|废弃小屋|化装舞会|午夜列车|错开的拼图|找到宝藏', 12),
  ('mystery-en', 'en', 'Mystery', 'Little Detectives', 'Clues, secret passages, and tiny mysteries.', 'magnifying glass|fingerprint|footprints|mystery note|secret letter|treasure map|old key|locked chest|combination lock|code book|flashlight|binoculars|security camera|detective hat|trench coat|dark sunglasses|fake mustache|secret passage|hidden door|trap floor|wall map|clue board|red string|lost necklace|forgotten glove|broken vase|empty picture frame|ladder by window|muddy footprint|dripping umbrella|night lighthouse|mystery footsteps|tracking dog|shadow on the roof|figure behind tree|letter at door|mystery package|treasure chest|gold coin|ancient scroll|clock tower|maze|spinning bookcase|basement|attic|empty cabin|masquerade ball|midnight train|missing puzzle piece|found treasure', 12),
  ('mystery-fr', 'fr', 'Enquête', 'Petits détectives', 'Indices, passages secrets et mini mystères.', 'loupe|empreinte digitale|traces de pas|note mystérieuse|lettre secrète|carte au trésor|vieille clé|coffre fermé|cadenas à code|carnet de codes|lampe torche|jumelles|caméra de sécurité|chapeau détective|imperméable|lunettes noires|fausse moustache|passage secret|porte cachée|trappe au sol|carte au mur|mur des indices|fil rouge|collier perdu|gant oublié|vase cassé|cadre vide|échelle à fenêtre|trace dans la boue|parapluie mouillé|phare de nuit|pas mystérieux|chien pisteur|ombre sur le toit|silhouette derrière|lettre sous la porte|colis mystérieux|coffre au trésor|pièce en or|vieux parchemin|tour horloge|labyrinthe|bibliothèque pivot|sous sol|grenier|cabane vide|bal masqué|train de minuit|pièce de puzzle|trésor retrouvé', 12),
  ('game-night-zh', 'zh-CN', '游戏', '游戏厅开黑', '从桌游到街机，画出一局快乐。', '游戏手柄|街机摇杆|像素爱心|游戏金币|宝箱|存档点|传送门|像素宝剑|魔法药水|生命值|双人游戏|游戏地图|迷宫入口|最终关卡|通关奖杯|任务卷轴|游戏背包|道具箱|赛车游戏|跳跃平台|弹跳蘑菇|移动方块|飞行背包|纸飞机比赛|桌上足球|飞镖盘|保龄球瓶|乒乓球拍|拼图|积木塔|棋盘|跳棋|国际象棋|围棋|五子棋|麻将牌|扑克牌|骰子塔|沙漏|翻牌游戏|抓娃娃机|扭蛋机|弹珠机|投篮机|打地鼠|碰碰车|旋转木马|射箭靶|游戏奖券|冠军奖杯', 13),
  ('game-night-en', 'en', 'Games', 'Game Night', 'From board games to arcade adventures.', 'game controller|arcade joystick|pixel heart|game coin|treasure chest|save point|portal|pixel sword|magic potion|health bar|two player game|game map|maze entrance|final level|victory trophy|quest scroll|game backpack|item box|racing game|jumping platform|bouncy mushroom|moving block|jetpack|paper plane race|table football|dartboard|bowling pins|ping pong paddle|jigsaw puzzle|block tower|game board|checkers|chess|go board|five in a row|mahjong tiles|playing cards|dice tower|hourglass|memory cards|claw machine|capsule machine|pinball machine|basketball arcade|whack a mole|bumper cars|carousel|archery target|prize tickets|champion cup', 13),
  ('game-night-fr', 'fr', 'Jeux', 'Soirée jeux', 'Des jeux de table aux bornes arcade.', 'manette de jeu|joystick arcade|coeur pixel|pièce de jeu|coffre au trésor|point de sauvegarde|portail|épée pixel|potion magique|barre de vie|jeu à deux|carte du jeu|entrée du labyrinthe|dernier niveau|trophée victoire|parchemin quête|sac du joueur|boîte à objets|jeu de course|plateforme saut|champignon rebond|bloc mobile|jetpack|course avion papier|baby foot|cible de fléchettes|quilles de bowling|raquette de ping|puzzle|tour de briques|plateau de jeu|dames|échecs|jeu de go|morpion|tuiles de mahjong|cartes à jouer|tour de dés|sablier|jeu de mémoire|machine à pinces|machine à capsules|flipper|panier arcade|jeu tape taupe|autos tamponneuses|manège|cible de tir|tickets gagnants|coupe du champion', 13),
  ('silly-combos-zh', 'zh-CN', '脑洞', '离谱画面生成器', '越不可能的组合，越容易笑出声。', '猫咪开飞机|企鹅卖冰淇淋|熊猫跳芭蕾|章鱼打鼓|大象坐滑板|恐龙吃火锅|外星人遛狗|机器人种花|月亮戴墨镜|太阳打喷嚏|云朵下雨伞|香蕉骑自行车|西瓜泡温泉|草莓打电话|汉堡练瑜伽|披萨弹吉他|闹钟睡懒觉|雨伞躲雨|冰箱穿棉袄|沙发跑马拉松|铅笔画自己|书包去旅行|咖啡杯洗澡|拖鞋跳舞|气球举重|蘑菇撑伞|仙人掌理发|向日葵晒太阳|雪人喝热茶|火山吃冰淇淋|鲸鱼骑摩托|螃蟹弹钢琴|海豚放风筝|青蛙坐地铁|狐狸开咖啡店|兔子当裁判|松鼠当海盗|狮子吹泡泡|长颈鹿玩滑梯|乌龟开赛车|扫帚学飞行|飞船堵车|城堡长脚|彩虹打结|星星钓鱼|地球打篮球|月球吹生日蜡烛|火箭吃面条|龙给花浇水|独角兽送快递', 14),
  ('silly-combos-en', 'en', 'Silly', 'Wild Mashups', 'Impossible scenes that are fun to draw.', 'cat flying a plane|penguin selling ice|panda doing ballet|octopus on drums|elephant on a board|dinosaur eating stew|alien walking a dog|robot planting seeds|moon in sunglasses|sneezing sun|cloud with umbrella|banana riding a bike|watermelon in a spa|strawberry on phone|burger doing yoga|pizza playing guitar|alarm clock sleeping|umbrella hiding rain|fridge in a coat|sofa running a race|pencil self sketch|backpack on vacation|coffee cup bathing|slippers dancing|strong balloon|mushroom with brolly|cactus at barber|sunflower sunbathing|snowman drinking tea|volcano eating ice|whale on a bike|crab playing piano|dolphin flying kite|frog on the subway|fox running a cafe|rabbit as referee|squirrel as pirate|lion blowing bubbles|giraffe on a slide|turtle racing cars|broom flying lesson|spaceship in traffic|castle with legs|tangled rainbow|star fishing|earth playing hoops|moon blowing candles|rocket with noodles|dragon watering|unicorn mail carrier', 14),
  ('silly-combos-fr', 'fr', 'Loufoque', 'Scènes loufoques', 'Des scènes impossibles et drôles à dessiner.', 'chat pilote un avion|manchot vend glaces|panda danse ballet|pieuvre batteuse|éléphant sur skate|dinosaure au resto|alien promène chien|robot plante fleurs|lune en lunettes|soleil éternue|nuage sous parapluie|banane à vélo|pastèque au spa|fraise au téléphone|burger fait yoga|pizza joue guitare|réveil endormi|parapluie sous pluie|frigo en manteau|canapé au marathon|crayon se dessine|sac à dos voyage|tasse prend un bain|pantoufles dansent|ballon soulève poids|champignon et pluie|cactus chez coiffeur|tournesol au soleil|bonhomme boit du thé|volcan mange glace|baleine sur moto|crabe joue piano|dauphin cerf volant|grenouille en métro|renard tient café|lapin arbitre|écureuil pirate|lion fait des bulles|girafe sur toboggan|tortue en course|balai fait du vol|vaisseau en bouchon|château avec jambes|arc en ciel noué|étoile à la pêche|terre joue au basket|lune souffle bougies|fusée mange nouilles|dragon arrose fleurs|licorne livre colis', 14)
) AS seed(id, locale, category, title, description, words, sort_order)
ON CONFLICT ("id") DO NOTHING;
