-- Eight additional themes per language, with 50 drawable words in each pack.
INSERT INTO "public"."DrawGuessWordBank" ("id", "locale", "category", "title", "description", "words", "sortOrder")
SELECT id, locale, category, title, description, string_to_array(words, '|'), sort_order
FROM (VALUES
('food-zh','zh-CN','美食','美食厨房','从早餐到甜点，越画越饿。','包子|饺子|面条|米饭|炒饭|火锅|烧烤|汉堡|披萨|寿司|三明治|热狗|炸鸡|薯条|煎蛋|荷包蛋|粥|馒头|油条|豆浆|冰淇淋|蛋糕|布丁|甜甜圈|巧克力|棒棒糖|爆米花|苹果|香蕉|西瓜|草莓|葡萄|菠萝|橙子|柠檬|胡萝卜|西红柿|玉米|蘑菇|南瓜|黄瓜|咖啡|奶茶|果汁|可乐|牛奶|茶壶|平底锅|电饭煲|烤箱',2),
('food-en','en','Food','Kitchen Feast','Breakfast, snacks, and desserts worth drawing.','dumpling|noodles|rice|fried rice|hot pot|barbecue|hamburger|pizza|sushi|sandwich|hot dog|fried chicken|fries|fried egg|porridge|toast|pancake|waffle|ice cream|cake|pudding|donut|chocolate|lollipop|popcorn|apple|banana|watermelon|strawberry|grapes|pineapple|orange|lemon|carrot|tomato|corn|mushroom|pumpkin|cucumber|coffee|milk tea|juice|soda|milk|teapot|frying pan|rice cooker|oven|cookie|cupcake',2),
('food-fr','fr','Cuisine','Festin en cuisine','Du petit déjeuner aux desserts.','ravioli|nouilles|riz|riz sauté|fondue|barbecue|hamburger|pizza|sushi|sandwich|hot-dog|poulet frit|frites|oeuf au plat|porridge|tartine|crêpe|gaufre|glace|gâteau|flan|beignet|chocolat|sucette|pop-corn|pomme|banane|pastèque|fraise|raisin|ananas|orange|citron|carotte|tomate|maïs|champignon|citrouille|concombre|café|thé au lait|jus|soda|lait|théière|poêle|cuiseur à riz|four|biscuit|petit gâteau',2),
('transport-zh','zh-CN','交通','出发吧','车轮、翅膀和水上的冒险。','自行车|三轮车|摩托车|电动车|滑板车|小汽车|出租车|公交车|校车|救护车|消防车|警车|卡车|货车|拖拉机|挖掘机|推土机|叉车|房车|赛车|地铁|火车|高铁|电车|缆车|过山车|飞机|直升机|热气球|滑翔伞|火箭|宇宙飞船|轮船|帆船|游艇|独木舟|潜水艇|橡皮艇|渡轮|雪橇|滑板|独轮车|马车|交通灯|斑马线|隧道|大桥|机场|车站|加油站',3),
('transport-en','en','Transport','On the Move','Wheels, wings, and voyages across water.','bicycle|tricycle|motorcycle|scooter|electric bike|car|taxi|bus|school bus|ambulance|fire truck|police car|truck|van|tractor|excavator|bulldozer|forklift|camper van|race car|subway|train|bullet train|tram|cable car|roller coaster|airplane|helicopter|hot air balloon|paraglider|rocket|spaceship|ship|sailboat|yacht|canoe|submarine|raft|ferry|sled|skateboard|unicycle|horse cart|traffic light|crosswalk|tunnel|bridge|airport|station|gas station',3),
('transport-fr','fr','Transport','En route','Des roues, des ailes et des voyages.','vélo|tricycle|moto|trottinette|vélo électrique|voiture|taxi|bus|bus scolaire|ambulance|camion de pompier|voiture de police|camion|fourgonnette|tracteur|pelleteuse|bulldozer|chariot élévateur|camping-car|voiture de course|métro|train|train rapide|tramway|téléphérique|montagnes russes|avion|hélicoptère|montgolfière|parapente|fusée|vaisseau spatial|navire|voilier|yacht|canoë|sous-marin|radeau|ferry|luge|skateboard|monocycle|calèche|feu tricolore|passage piéton|tunnel|pont|aéroport|gare|station essence',3),
('places-zh','zh-CN','场所','城市漫游','画出朋友熟悉或想去的地方。','学校|教室|图书馆|书店|超市|菜市场|商场|咖啡店|餐厅|面包店|电影院|剧院|博物馆|美术馆|动物园|水族馆|游乐园|公园|植物园|医院|药店|银行|邮局|警察局|消防站|火车站|地铁站|机场|港口|酒店|民宿|露营地|海滩|灯塔|山顶|瀑布|湖泊|森林|农场|花园|体育馆|游泳馆|足球场|篮球场|健身房|厨房|卧室|浴室|屋顶|树屋',4),
('places-en','en','Places','City Wander','Places your friends know or dream of visiting.','school|classroom|library|bookstore|supermarket|market|mall|coffee shop|restaurant|bakery|cinema|theater|museum|art gallery|zoo|aquarium|amusement park|park|botanical garden|hospital|pharmacy|bank|post office|police station|fire station|train station|subway station|airport|harbor|hotel|guesthouse|campsite|beach|lighthouse|mountain top|waterfall|lake|forest|farm|garden|stadium|swimming pool|soccer field|basketball court|gym|kitchen|bedroom|bathroom|rooftop|treehouse',4),
('places-fr','fr','Lieux','Balade en ville','Des lieux connus ou rêvés à dessiner.','école|classe|bibliothèque|librairie|supermarché|marché|centre commercial|café|restaurant|boulangerie|cinéma|théâtre|musée|galerie|zoo|aquarium|parc de loisirs|parc|jardin botanique|hôpital|pharmacie|banque|poste|commissariat|caserne|gare|station de métro|aéroport|port|hôtel|maison hôte|camping|plage|phare|sommet|cascade|lac|forêt|ferme|jardin|stade|piscine|terrain de foot|terrain de basket|salle de sport|cuisine|chambre|salle de bain|toit|cabane',4),
('jobs-zh','zh-CN','职业','谁在上班','猜猜画里的人今天做什么工作。','医生|护士|老师|学生|警察|消防员|厨师|服务员|面包师|咖啡师|理发师|摄影师|画家|设计师|程序员|工程师|建筑师|记者|主持人|演员|歌手|舞者|音乐家|作家|司机|飞行员|空乘|船长|宇航员|科学家|农民|园丁|兽医|牙医|药剂师|律师|法官|邮递员|快递员|清洁工|木匠|电工|水管工|裁缝|导游|运动员|裁判|魔术师|小丑|救生员',5),
('jobs-en','en','Jobs','At Work','Who is doing what today?','doctor|nurse|teacher|student|police officer|firefighter|chef|waiter|baker|barista|hairdresser|photographer|painter|designer|programmer|engineer|architect|reporter|presenter|actor|singer|dancer|musician|writer|driver|pilot|flight attendant|captain|astronaut|scientist|farmer|gardener|veterinarian|dentist|pharmacist|lawyer|judge|mail carrier|courier|cleaner|carpenter|electrician|plumber|tailor|tour guide|athlete|referee|magician|clown|lifeguard',5),
('jobs-fr','fr','Métiers','Au travail','Devinez le métier de chaque personnage.','médecin|infirmière|professeur|élève|policier|pompier|cuisinier|serveur|boulanger|barista|coiffeur|photographe|peintre|designer|programmeur|ingénieur|architecte|journaliste|présentateur|acteur|chanteur|danseur|musicien|écrivain|chauffeur|pilote|hôtesse|capitaine|astronaute|scientifique|fermier|jardinier|vétérinaire|dentiste|pharmacien|avocat|juge|facteur|livreur|agent de ménage|menuisier|électricien|plombier|couturier|guide|athlète|arbitre|magicien|clown|sauveteur',5),
('sports-zh','zh-CN','运动','动起来','比赛、运动器材和高能动作。','足球|篮球|排球|网球|乒乓球|羽毛球|棒球|橄榄球|高尔夫|保龄球|台球|游泳|跳水|冲浪|划船|赛艇|跑步|马拉松|跨栏|接力跑|跳高|跳远|撑杆跳|体操|瑜伽|攀岩|滑雪|滑冰|花样滑冰|冰球|拳击|摔跤|柔道|跆拳道|击剑|射箭|射击|举重|自行车赛|赛车|滑板|蹦床|跳绳|呼啦圈|飞盘|拔河|啦啦队|领奖台|金牌|火炬',6),
('sports-en','en','Sports','Move It','Sports, gear, and action moments.','soccer|basketball|volleyball|tennis|table tennis|badminton|baseball|rugby|golf|bowling|pool|swimming|diving|surfing|rowing|kayaking|running|marathon|hurdles|relay race|high jump|long jump|pole vault|gymnastics|yoga|rock climbing|skiing|ice skating|figure skating|ice hockey|boxing|wrestling|judo|taekwondo|fencing|archery|shooting|weightlifting|cycling|racing|skateboarding|trampoline|jump rope|hula hoop|frisbee|tug of war|cheerleader|podium|gold medal|torch',6),
('sports-fr','fr','Sports','Bougez','Sports, objets et gestes en mouvement.','football|basket|volley|tennis|tennis de table|badminton|baseball|rugby|golf|bowling|billard|natation|plongeon|surf|aviron|kayak|course|marathon|haies|relais|saut en hauteur|saut en longueur|perche|gymnastique|yoga|escalade|ski|patinage|patinage artistique|hockey|boxe|lutte|judo|taekwondo|escrime|tir à arc|tir sportif|haltérophilie|cyclisme|course auto|skateboard|trampoline|corde à sauter|cerceau|frisbee|tir à la corde|pom-pom girl|podium|médaille|flambeau',6),
('plants-zh','zh-CN','植物','花园奇遇','花草树木和田园小物。','玫瑰|向日葵|郁金香|百合|樱花|荷花|菊花|薰衣草|蒲公英|仙人掌|多肉植物|竹子|松树|枫树|柳树|椰子树|苹果树|橘子树|桃树|银杏树|蘑菇|苔藓|藤蔓|四叶草|薄荷|罗勒|迷迭香|麦穗|稻田|玉米田|南瓜|番茄|胡萝卜|茄子|辣椒|黄瓜|草莓|蓝莓|葡萄藤|西瓜|菠萝|柠檬|樱桃|桃子|梨子|花盆|洒水壶|温室|树桩|秋叶',7),
('plants-en','en','Plants','Garden Quest','Flowers, trees, and little garden treasures.','rose|sunflower|tulip|lily|cherry blossom|lotus|daisy|lavender|dandelion|cactus|succulent|bamboo|pine tree|maple tree|willow tree|palm tree|apple tree|orange tree|peach tree|ginkgo tree|mushroom|moss|vine|four leaf clover|mint|basil|rosemary|wheat|rice field|cornfield|pumpkin|tomato|carrot|eggplant|pepper|cucumber|strawberry|blueberry|grapevine|watermelon|pineapple|lemon|cherry|peach|pear|flowerpot|watering can|greenhouse|tree stump|autumn leaf',7),
('plants-fr','fr','Plantes','Aventure au jardin','Fleurs, arbres et petits trésors du jardin.','rose|tournesol|tulipe|lys|cerisier|lotus|marguerite|lavande|pissenlit|cactus|plante grasse|bambou|pin|érable|saule|palmier|pommier|oranger|pêcher|ginkgo|champignon|mousse|vigne|trèfle|menthe|basilic|romarin|blé|rizière|champ de maïs|citrouille|tomate|carotte|aubergine|poivron|concombre|fraise|myrtille|grappe de raisin|pastèque|ananas|citron|cerise|pêche|poire|pot de fleurs|arrosoir|serre|souche|feuille morte',7),
('funny-zh','zh-CN','搞笑','翻车现场','谁能把这些尴尬时刻画出来？','踩到香蕉皮|打喷嚏|忘带钥匙|穿反衣服|迟到|坐过站|手机掉水里|咖啡洒了|蛋糕糊脸|鞋带散开|被鸽子追|排队排错|认错人|走错教室|忘词|唱歌跑调|跳舞摔倒|拍照闭眼|雨伞翻了|吹灭蜡烛失败|气球飞走|冰淇淋掉地|头发炸开|打嗝|睡过头|撞上玻璃门|踩进水坑|帽子被风吹走|假装没看见|被猫嫌弃|被狗拖着跑|偷吃被发现|把盐当糖|画画画歪|剪坏头发|鞋子穿错|拿错行李|电梯关门|拍照抢镜|自拍变鬼脸|跳绳打结|放风筝挂树|做饭冒烟|泡面太辣|手机没电|麦克风没开|被蚊子咬|睡觉打呼|笑到流泪|倒着看地图',8),
('funny-en','en','Funny','Oops Moments','Draw a tiny disaster and make everyone laugh.','banana slip|sneeze|lost keys|inside out shirt|late for school|missed stop|wet phone|spilled coffee|cake face|loose shoelace|chased by pigeon|wrong line|mistaken person|wrong classroom|forgot lyrics|singing off key|dance fall|closed eyes photo|broken umbrella|failed candle blow|lost balloon|dropped ice cream|wild hair|hiccups|overslept|glass door bump|puddle splash|flying hat|pretend not to see|grumpy cat|dog pulling leash|caught snacking|salty coffee|crooked drawing|bad haircut|mismatched shoes|wrong suitcase|closing elevator|photo bomber|silly selfie|tangled jump rope|kite in a tree|smoky cooking|spicy noodles|dead phone|muted microphone|mosquito bite|loud snoring|laughing tears|upside down map',8),
('funny-fr','fr','Drôle','Petits ratés','Des scènes gênantes et amusantes à dessiner.','glissade|éternuement|clés perdues|chemise à envers|en retard|arrêt manqué|téléphone mouillé|café renversé|gâteau au visage|lacet défait|pigeon poursuivant|mauvaise file|mauvaise personne|mauvaise classe|paroles oubliées|chant faux|chute en danse|photo yeux fermés|parapluie cassé|bougie intacte|ballon envolé|glace tombée|cheveux en bataille|hoquet|grasse matinée|porte vitrée|éclaboussure|chapeau envolé|regard détourné|chat boudeur|chien qui tire|goûter en cachette|sel dans le café|dessin de travers|coupe ratée|souliers différents|mauvaise valise|ascenseur fermé|intrus sur photo|grimace selfie|corde emmêlée|cerf-volant coincé|cuisine enfumée|nouilles piquantes|batterie vide|micro coupé|piqûre de moustique|ronflement|fou rire|carte à envers',8),
('fantasy-zh','zh-CN','奇幻','脑洞冒险','魔法、太空和不可能的朋友。','独角兽|巨龙|精灵|仙女|巫师|女巫|魔法帽|魔法棒|水晶球|魔法书|飞毯|扫帚飞行|城堡|藏宝图|宝箱|海盗船|美人鱼|海怪|章鱼怪|巨人|小矮人|机器人|机械猫|外星人|飞碟|宇航员|月球基地|火星车|星球|银河|黑洞|彗星|流星雨|时间机器|传送门|隐身衣|会飞的鱼|会说话的树|糖果屋|云上城堡|水下城市|彩虹桥|发光蘑菇|冰雪女王|火焰凤凰|石头巨人|龙蛋|魔法森林|秘密花园|许愿池',9),
('fantasy-en','en','Fantasy','Wild Imagination','Magic, space, and impossible friends.','unicorn|dragon|elf|fairy|wizard|witch|magic hat|magic wand|crystal ball|spell book|flying carpet|flying broom|castle|treasure map|treasure chest|pirate ship|mermaid|sea monster|octopus monster|giant|dwarf|robot|robot cat|alien|flying saucer|astronaut|moon base|mars rover|planet|galaxy|black hole|comet|meteor shower|time machine|portal|invisibility cloak|flying fish|talking tree|candy house|sky castle|underwater city|rainbow bridge|glowing mushroom|ice queen|fire phoenix|stone giant|dragon egg|magic forest|secret garden|wishing well',9),
('fantasy-fr','fr','Fantaisie','Grande imagination','Magie, espace et amis impossibles.','licorne|dragon|elfe|fée|magicien|sorcière|chapeau magique|baguette magique|boule de cristal|grimoire|tapis volant|balai volant|château|carte au trésor|coffre au trésor|navire pirate|sirène|monstre marin|pieuvre géante|géant|nain|robot|chat robot|alien|soucoupe volante|astronaute|base lunaire|rover martien|planète|galaxie|trou noir|comète|pluie de météores|machine à voyager|portail|cape invisible|poisson volant|arbre parlant|maison en bonbons|château du ciel|ville sous marine|pont arc en ciel|champignon lumineux|reine des neiges|phénix|géant de pierre|oeuf de dragon|forêt magique|jardin secret|puits à souhaits',9)
) AS seed(id, locale, category, title, description, words, sort_order)
ON CONFLICT ("id") DO NOTHING;
