const copies = {
  "zh-CN": {
    managersTitle: "票券负责人",
    managersHelp: "负责人可邀请核销员并查看这类票的全部核销记录。",
    merchantOwner: "关联门店店主",
    merchantOwnerHint: "门店归属有效时，店主自动拥有管理与核销权限。",
    addManager: "指定负责人",
    staffTitle: "核销人员",
    staffHelp: "核销员只负责这类票，可持有 0 张票。",
    inviteStaff: "邀请核销员",
    friendCode: "对方的 6 位 Friemi 码",
    friendCodePlaceholder: "000 000",
    active: "已生效",
    pending: "等待接受",
    revoked: "已撤销",
    revoke: "撤销权限",
    emptyManagers: "还没有指定其他负责人。",
    emptyStaff: "还没有核销员。",
    actionFailed: "操作未完成，请核对账号或稍后重试。",
    alreadyAssigned: "这个账号已有该权限。",
    selfAssigned: "不能给自己发送核销邀请。",
    accountMissing: "没有找到这个 Friemi 账号。",
    managerGranted: "负责人已指定。",
    staffInvited: "邀请已发送，对方接受后生效。",
    accessRevoked: "权限已撤销。",
    roleAdmin: "管理员指定",
    roleAllocation: "票券分配",
    roleInvitation: "受邀加入",
    historyTitle: "核销记录",
    historyEmpty: "还没有核销记录。",
    historyCount: (total: number) => `共 ${total} 条`,
    redeemedBy: (name: string) => `核销员：${name}`,
    holder: (name: string) => `持票人：${name}`,
    methodQr: "扫码",
    methodManual: "手输码",
    methodUnknown: "历史记录",
    previous: "上一页",
    next: "下一页",
    page: (current: number, total: number) => `第 ${current} / ${total} 页`,
  },
  en: {
    managersTitle: "Ticket managers",
    managersHelp: "Managers can invite check-in staff and view this ticket’s full history.",
    merchantOwner: "Linked store owner",
    merchantOwnerHint: "The owner can manage and check in this ticket while the store is linked.",
    addManager: "Assign manager",
    staffTitle: "Check-in staff",
    staffHelp: "Staff can check in this ticket with zero tickets in their bag.",
    inviteStaff: "Invite staff member",
    friendCode: "Their 6-digit Friemi code",
    friendCodePlaceholder: "000 000",
    active: "Active",
    pending: "Awaiting acceptance",
    revoked: "Revoked",
    revoke: "Revoke access",
    emptyManagers: "No additional manager has been assigned.",
    emptyStaff: "No check-in staff yet.",
    actionFailed: "Could not complete this action. Check the account and try again.",
    alreadyAssigned: "This account already has access.",
    selfAssigned: "You cannot invite yourself to check in tickets.",
    accountMissing: "No Friemi account was found for this code.",
    managerGranted: "Manager assigned.",
    staffInvited: "Invitation sent. Access begins when they accept.",
    accessRevoked: "Access revoked.",
    roleAdmin: "Assigned by admin",
    roleAllocation: "Ticket allocation",
    roleInvitation: "Invited",
    historyTitle: "Check-in history",
    historyEmpty: "No tickets have been checked in yet.",
    historyCount: (total: number) => `${total} records`,
    redeemedBy: (name: string) => `Checked in by ${name}`,
    holder: (name: string) => `Holder: ${name}`,
    methodQr: "QR scan",
    methodManual: "Manual code",
    methodUnknown: "Earlier record",
    previous: "Previous",
    next: "Next",
    page: (current: number, total: number) => `Page ${current} of ${total}`,
  },
  fr: {
    managersTitle: "Responsables du billet",
    managersHelp: "Ils peuvent inviter des contrôleurs et consulter tout l’historique.",
    merchantOwner: "Propriétaire de la boutique",
    merchantOwnerHint: "Le propriétaire peut gérer et contrôler ce billet tant que la boutique est associée.",
    addManager: "Désigner un responsable",
    staffTitle: "Équipe de contrôle",
    staffHelp: "Un contrôleur peut valider ce billet sans en posséder.",
    inviteStaff: "Inviter un contrôleur",
    friendCode: "Son code Friemi à 6 chiffres",
    friendCodePlaceholder: "000 000",
    active: "Actif",
    pending: "En attente",
    revoked: "Révoqué",
    revoke: "Révoquer l’accès",
    emptyManagers: "Aucun autre responsable n’a été désigné.",
    emptyStaff: "Aucun contrôleur pour le moment.",
    actionFailed: "Action impossible. Vérifiez le compte et réessayez.",
    alreadyAssigned: "Ce compte dispose déjà de cet accès.",
    selfAssigned: "Vous ne pouvez pas vous inviter vous-même.",
    accountMissing: "Aucun compte Friemi trouvé pour ce code.",
    managerGranted: "Responsable désigné.",
    staffInvited: "Invitation envoyée. L’accès commencera après acceptation.",
    accessRevoked: "Accès révoqué.",
    roleAdmin: "Désigné par l’administration",
    roleAllocation: "Attribution de billets",
    roleInvitation: "Invité",
    historyTitle: "Historique des contrôles",
    historyEmpty: "Aucun billet contrôlé pour le moment.",
    historyCount: (total: number) => `${total} opérations`,
    redeemedBy: (name: string) => `Contrôlé par ${name}`,
    holder: (name: string) => `Titulaire : ${name}`,
    methodQr: "Scan QR",
    methodManual: "Code saisi",
    methodUnknown: "Ancien enregistrement",
    previous: "Précédent",
    next: "Suivant",
    page: (current: number, total: number) => `Page ${current} sur ${total}`,
  },
} as const;

export function getAdminTicketAccessCopy(locale: string) {
  return copies[locale === "en" || locale === "fr" ? locale : "zh-CN"];
}
