export function getInventoryCopy(locale: string) {
  if (locale === "fr") {
    return {
      admin: "Distribution des billets",
      adminIntro:
        "Créez un lot, attribuez les billets aux comptes choisis. Si le cadeau est autorisé, leurs détenteurs pourront les offrir depuis leur sac.",
      adminBatch: "Lots de billets",
      adminBatchAvailable: (count: number) => `${count} restants`,
      adminEmptyTitle: "Créez votre premier lot",
      adminIssueHint:
        "Vérifiez le compte destinataire par code Friemi ou QR, puis indiquez le nombre de billets à attribuer.",
      adminIssueQuantity: "Nombre de billets à attribuer",
      adminIssueForBatch: (title: string) => `Attribuer : ${title}`,
      adminIssueLimit: (count: number) =>
        `Maximum pour cette attribution : ${count}`,
      adminIssueReview: (
        count: number,
        title: string,
        name: string,
        code: string,
      ) =>
        `${count} billets « ${title} » seront ajoutés au sac de ${name} (code Friemi ${code}). Vérifiez ces informations avant de confirmer.`,
      adminIssueConfirm: "Confirmer l'attribution",
      adminIssueSuccessHistory: "Voir l'attribution dans l'historique",
      adminIssueNoStock:
        "Le stock a changé. Actualisez la page, puis ajustez la quantité.",
      adminIssueNotFound:
        "Ce compte n'est plus disponible. Recherchez de nouveau son code Friemi.",
      adminIssueInvalid:
        "Vérifiez le compte et la quantité avant de réessayer.",
      adminSupplyPlaceholder: "Ex. 1 000",
      adminSupplyHint:
        "La création du lot n'ajoute aucun billet aux comptes. Attribuez-les ensuite.",
      adminNewBatch: "Nouveau lot",
      adminSoldOut: "Tous les billets de ce lot ont été attribués.",
      adminIssueHistory: "Attributions par l'administration",
      adminIssueEmpty:
        "Aucune attribution. Les billets attribués apparaîtront ici.",
      adminHistoryAllocationTo: (name: string) => `Attribués à ${name}`,
      adminHistoryBy: (actor: string) => `Par ${actor}`,
      adminHistoryTicketCount: (count: number) =>
        `${count} billet${count > 1 ? "s" : ""}`,
      adminGiftHistory: "Cadeaux entre comptes",
      adminGiftEmpty:
        "Aucun cadeau. Les billets offerts par les détenteurs apparaîtront ici.",
      adminGiftStatus: "Cadeau entre comptes :",
      adminGiftEnabled: "Autorisé",
      adminGiftDisabled: "Suspendu",
      adminGiftSettingsHint:
        "Ce réglage s'applique aussi aux billets non offerts déjà attribués. Un billet déjà offert ne peut jamais être offert à nouveau.",
      adminGiftFormHint:
        "Une fois activé, le détenteur peut offrir chaque billet une seule fois. Le désactiver empêche tout cadeau, même après attribution.",
      available: "Disponibles à offrir",
      allocated: "Attribués",
      back: "Retour au sac",
      create: "Créer un lot",
      createError: "Le lot n'a pas pu être créé.",
      created: "Lot créé.",
      description: "Description",
      disableGifting: "Suspendre les cadeaux",
      enableGifting: "Autoriser les cadeaux",
      gift: "Offrir un billet",
      giftError: "Le billet n'a pas pu être envoyé.",
      gifted: "Billet envoyé à",
      giftHistory: "Historique des cadeaux",
      giftable: "Autoriser le cadeau",
      historyEmpty: "Aucun billet offert pour le moment.",
      issue: "Attribuer des billets",
      issueError: "Les billets n'ont pas pu être attribués.",
      issued: "Billets attribués à",
      methodCode: "Code Friemi",
      methodQr: "QR de profil",
      next: "Suivant",
      noTickets: "Aucun billet disponible à offrir.",
      owned: "Dans le sac",
      previous: "Précédent",
      quantity: "Quantité",
      remaining: "À attribuer",
      serial: "Billet n°",
      supply: "Nombre total de billets",
      title: "Nom du billet",
      ticket: "Billet",
      ticketHint: "Un billet ne peut être offert qu'une seule fois.",
      ticketList: "Billets dans votre sac",
      transferLocked: "Ce billet a déjà été offert et ne peut plus l'être.",
      viewHistory: "Voir les attributions et les cadeaux",
    };
  }
  if (locale === "en") {
    return {
      admin: "Ticket distribution",
      adminIntro:
        "Create a batch and allocate tickets to selected accounts. When gifting is allowed, holders can gift them from their bags.",
      adminBatch: "Ticket batches",
      adminBatchAvailable: (count: number) => `${count} left`,
      adminEmptyTitle: "Create your first batch",
      adminIssueHint:
        "Verify the receiving account by Friemi code or QR, then enter the number of tickets to allocate.",
      adminIssueQuantity: "Tickets to allocate",
      adminIssueForBatch: (title: string) => `Allocate: ${title}`,
      adminIssueLimit: (count: number) =>
        `Maximum for this allocation: ${count}`,
      adminIssueReview: (
        count: number,
        title: string,
        name: string,
        code: string,
      ) =>
        `${count} ${title} tickets will be added to ${name}'s bag (Friemi code ${code}). Check these details before confirming.`,
      adminIssueConfirm: "Confirm allocation",
      adminIssueSuccessHistory: "View allocation in history",
      adminIssueNoStock:
        "Stock has changed. Refresh the page and adjust the quantity.",
      adminIssueNotFound:
        "This account is no longer available. Look up its Friemi code again.",
      adminIssueInvalid: "Check the account and quantity, then try again.",
      adminSupplyPlaceholder: "e.g. 1000",
      adminSupplyHint:
        "Creating a batch does not add tickets to any account. Allocate them next.",
      adminNewBatch: "New batch",
      adminSoldOut: "All tickets in this batch have been allocated.",
      adminIssueHistory: "Admin allocations",
      adminIssueEmpty:
        "No allocations yet. Allocated tickets will appear here.",
      adminHistoryAllocationTo: (name: string) => `Allocated to ${name}`,
      adminHistoryBy: (actor: string) => `By ${actor}`,
      adminHistoryTicketCount: (count: number) =>
        `${count} ticket${count === 1 ? "" : "s"}`,
      adminGiftHistory: "Gifts between accounts",
      adminGiftEmpty:
        "No gifts yet. Tickets gifted by holders will appear here.",
      adminGiftStatus: "Gifting between accounts:",
      adminGiftEnabled: "Allowed",
      adminGiftDisabled: "Paused",
      adminGiftSettingsHint:
        "This also affects allocated tickets that have not been gifted. A ticket already gifted can never be gifted again.",
      adminGiftFormHint:
        "When enabled, a holder can gift each ticket once. Disabling it stops gifting even after allocation.",
      available: "Available to gift",
      allocated: "Allocated",
      back: "Back to bag",
      create: "Create ticket batch",
      createError: "Could not create the ticket batch.",
      created: "Ticket batch created.",
      description: "Description",
      disableGifting: "Pause gifting",
      enableGifting: "Allow gifting",
      gift: "Gift one ticket",
      giftError: "Could not send the ticket.",
      gifted: "Ticket sent to",
      giftHistory: "Gift history",
      giftable: "Allow gifting",
      historyEmpty: "No tickets have been gifted yet.",
      issue: "Allocate tickets",
      issueError: "Could not allocate tickets.",
      issued: "Tickets allocated to",
      methodCode: "Friemi code",
      methodQr: "Profile QR",
      next: "Next",
      noTickets: "No tickets left to gift.",
      owned: "In your bag",
      previous: "Previous",
      quantity: "Quantity",
      remaining: "Unallocated",
      serial: "Ticket #",
      supply: "Total tickets",
      title: "Ticket name",
      ticket: "Ticket",
      ticketHint: "Each ticket can only be gifted once.",
      ticketList: "Tickets in your bag",
      transferLocked:
        "This ticket was already gifted and cannot be gifted again.",
      viewHistory: "View allocations and gifts",
    };
  }
  return {
    admin: "票券分发",
    adminIntro:
      "先创建批次，再分配给指定账户；允许赠送时，持有人可从背包送票。",
    adminBatch: "票券批次",
    adminBatchAvailable: (count: number) => `剩余 ${count} 张`,
    adminEmptyTitle: "创建第一批票券",
    adminIssueHint: "通过 Friemi 码或扫码确认接收账户，再填写分配数量。",
    adminIssueQuantity: "本次分配数量",
    adminIssueForBatch: (title: string) => `分配「${title}」`,
    adminIssueLimit: (count: number) => `本次最多分配 ${count} 张`,
    adminIssueReview: (
      count: number,
      title: string,
      name: string,
      code: string,
    ) =>
      `将 ${count} 张「${title}」放入 ${name}（Friemi 码 ${code}）的背包。请核对票券、账户和数量。`,
    adminIssueConfirm: "确认分配票券",
    adminIssueSuccessHistory: "在历史中查看这次分配",
    adminIssueNoStock: "库存已变化，请刷新页面并调整分配数量。",
    adminIssueNotFound: "这个账户已不可用，请重新查找 Friemi 码。",
    adminIssueInvalid: "请重新核对账户和数量后再试。",
    adminSupplyPlaceholder: "例如 1000",
    adminSupplyHint: "创建批次后，票还未进入任何账户；下一步再按数量分配。",
    adminNewBatch: "新建批次",
    adminSoldOut: "这一批票券已全部分配。",
    adminIssueHistory: "管理员分配记录",
    adminIssueEmpty: "还没有分配记录。完成分配后会显示在这里。",
    adminHistoryAllocationTo: (name: string) => `分配给 ${name}`,
    adminHistoryBy: (actor: string) => `由 ${actor} 分配`,
    adminHistoryTicketCount: (count: number) => `${count} 张`,
    adminGiftHistory: "账户间赠送记录",
    adminGiftEmpty: "还没有赠送记录。持有人送票后会显示在这里。",
    adminGiftStatus: "账户间赠送：",
    adminGiftEnabled: "已允许",
    adminGiftDisabled: "已暂停",
    adminGiftSettingsHint:
      "此设置也影响已分配但尚未赠送的票；赠送过的票始终不能再赠送。",
    adminGiftFormHint:
      "开启后，持有人可将每张票赠送一次；关闭后，即使已分配也无法赠送。",
    available: "可赠送",
    allocated: "已分配",
    back: "返回背包",
    create: "创建票券批次",
    createError: "创建票券失败，请检查填写内容。",
    created: "票券批次已创建。",
    description: "说明",
    disableGifting: "暂停赠送",
    enableGifting: "允许赠送",
    gift: "赠送一张票",
    giftError: "票券未能送出，请稍后重试。",
    gifted: "已将票券赠送给",
    giftHistory: "赠送历史",
    giftable: "允许赠送",
    historyEmpty: "还没有赠送记录。",
    issue: "分配票券",
    issueError: "票券分配失败，请稍后重试。",
    issued: "已分配票券给",
    methodCode: "Friemi 码",
    methodQr: "个人二维码",
    next: "下一页",
    noTickets: "目前没有可赠送的票券。",
    owned: "背包持有",
    previous: "上一页",
    quantity: "数量",
    remaining: "待分配",
    serial: "票号",
    supply: "票券总量",
    title: "票券名称",
    ticket: "酒会票券",
    ticketHint: "每张票只能赠送一次，收到后不可继续赠送。",
    ticketList: "背包中的票券",
    transferLocked: "这张票已经赠送过，不能再次赠送。",
    viewHistory: "查看分配与赠送记录",
  };
}
