export function getInventoryCopy(locale: string) {
  if (locale === "fr") {
    return {
      admin: "Distribution des billets",
      adminIntro:
        "Créez un lot, puis répartissez les billets entre les organisateurs.",
      adminBatch: "Lots de billets",
      adminEmptyTitle: "Créez votre premier lot",
      adminIssueHint:
        "Trouvez un compte par code Friemi ou QR, puis choisissez la quantité.",
      adminNewBatch: "Nouveau lot",
      adminSoldOut: "Tous les billets de ce lot ont été attribués.",
      adminIssueHistory: "Attributions aux comptes",
      adminIssueEmpty: "Aucun billet attribué pour le moment.",
      available: "Disponibles à offrir",
      allocated: "Attribués",
      back: "Retour au sac",
      create: "Créer un lot",
      createError: "Le lot n'a pas pu être créé.",
      created: "Lot créé.",
      description: "Description",
      disableGifting: "Désactiver le cadeau",
      enableGifting: "Autoriser le cadeau",
      gift: "Offrir un billet",
      giftError: "Le billet n'a pas pu être envoyé.",
      gifted: "Billet envoyé à",
      giftHistory: "Historique des cadeaux",
      giftable: "Autoriser le cadeau",
      historyEmpty: "Aucun billet offert pour le moment.",
      issue: "Attribuer des billets",
      issueError: "Les billets n'ont pas pu être attribués.",
      issued: "Billets attribués à",
      methodCode: "Code Friemi",
      methodQr: "QR de profil",
      next: "Suivant",
      noTickets: "Aucun billet disponible à offrir.",
      owned: "Dans le sac",
      previous: "Précédent",
      quantity: "Quantité",
      remaining: "À attribuer",
      serial: "Billet n°",
      supply: "Nombre total de billets",
      title: "Nom du billet",
      ticket: "Billet",
      ticketHint: "Un billet ne peut être offert qu'une seule fois.",
      ticketList: "Billets dans votre sac",
      transferLocked: "Ce billet a déjà été offert et ne peut plus l'être.",
      viewHistory: "Voir les détails et l'historique",
    };
  }
  if (locale === "en") {
    return {
      admin: "Ticket distribution",
      adminIntro: "Create a ticket batch, then allocate tickets to organizers.",
      adminBatch: "Ticket batches",
      adminEmptyTitle: "Create your first batch",
      adminIssueHint:
        "Find an account by Friemi code or QR, then choose the quantity.",
      adminNewBatch: "New batch",
      adminSoldOut: "All tickets in this batch have been allocated.",
      adminIssueHistory: "Allocations to accounts",
      adminIssueEmpty: "No tickets have been allocated yet.",
      available: "Available to gift",
      allocated: "Allocated",
      back: "Back to bag",
      create: "Create ticket batch",
      createError: "Could not create the ticket batch.",
      created: "Ticket batch created.",
      description: "Description",
      disableGifting: "Disable gifting",
      enableGifting: "Enable gifting",
      gift: "Gift one ticket",
      giftError: "Could not send the ticket.",
      gifted: "Ticket sent to",
      giftHistory: "Gift history",
      giftable: "Allow gifting",
      historyEmpty: "No tickets have been gifted yet.",
      issue: "Allocate tickets",
      issueError: "Could not allocate tickets.",
      issued: "Tickets allocated to",
      methodCode: "Friemi code",
      methodQr: "Profile QR",
      next: "Next",
      noTickets: "No tickets left to gift.",
      owned: "In your bag",
      previous: "Previous",
      quantity: "Quantity",
      remaining: "Unallocated",
      serial: "Ticket #",
      supply: "Total tickets",
      title: "Ticket name",
      ticket: "Ticket",
      ticketHint: "Each ticket can only be gifted once.",
      ticketList: "Tickets in your bag",
      transferLocked:
        "This ticket was already gifted and cannot be gifted again.",
      viewHistory: "View details and history",
    };
  }
  return {
    admin: "票券分发",
    adminIntro: "先创建票券批次，再按数量分配到一个或多个举办人账户。",
    adminBatch: "票券批次",
    adminEmptyTitle: "创建第一批票券",
    adminIssueHint: "输入 Friemi 码或扫码确认账户，再选择分配数量。",
    adminNewBatch: "新建批次",
    adminSoldOut: "这一批票券已全部分配。",
    adminIssueHistory: "账户分发记录",
    adminIssueEmpty: "还没有分发记录。",
    available: "可赠送",
    allocated: "已分配",
    back: "返回背包",
    create: "创建票券批次",
    createError: "创建票券失败，请检查填写内容。",
    created: "票券批次已创建。",
    description: "说明",
    disableGifting: "关闭赠送",
    enableGifting: "开启赠送",
    gift: "赠送一张票",
    giftError: "票券未能送出，请稍后重试。",
    gifted: "已将票券赠送给",
    giftHistory: "赠送历史",
    giftable: "允许赠送",
    historyEmpty: "还没有赠送记录。",
    issue: "分配票券",
    issueError: "票券分配失败，请稍后重试。",
    issued: "已分配票券给",
    methodCode: "Friemi 码",
    methodQr: "个人二维码",
    next: "下一页",
    noTickets: "目前没有可赠送的票券。",
    owned: "背包持有",
    previous: "上一页",
    quantity: "数量",
    remaining: "待分配",
    serial: "票号",
    supply: "票券总量",
    title: "票券名称",
    ticket: "酒会票券",
    ticketHint: "每张票只能赠送一次，收到后不可继续赠送。",
    ticketList: "背包中的票券",
    transferLocked: "这张票已经赠送过，不能再次赠送。",
    viewHistory: "查看票券与历史",
  };
}
