export function getTicketRedemptionCopy(locale: string) {
  if (locale === "fr") {
    return {
      alreadyRedeemed: "Ce billet a déjà été contrôlé.",
      back: "Retour",
      backToBag: "Retour aux billets",
      checkIn: "Contrôler un billet",
      confirm: "Confirmer le contrôle",
      confirmHint:
        "Vérifiez le numéro et le titulaire. Cette action est définitive.",
      copy: "Copier le lien",
      copied: "Lien copié",
      enterCode: "Coller le code ou le lien du billet",
      expired: "Ce code a expiré. Demandez un nouveau code au titulaire.",
      generate: "Afficher le code de contrôle",
      generatedHint:
        "Montrez ce QR code à l'organisateur. Il expire rapidement.",
      holder: "Titulaire",
      invalid: "Ce code de billet est introuvable ou invalide.",
      mismatch: "Ce billet n'appartient pas à cet événement.",
      myTicket: "Mon billet",
      newTickets: "Nouveaux billets",
      noCamera:
        "La caméra est indisponible. Collez le lien du billet ci-dessous.",
      open: "Ouvrir le billet",
      pageTitle: "Contrôle des billets",
      processing: "Contrôle en cours…",
      redeemed: "Billet contrôlé",
      redeemedNoGift:
        "Aucun billet à offrir. Un billet contrôlé ou déjà offert ne peut plus être transféré.",
      refresh: "Actualiser le code",
      scan: "Scanner un billet",
      scanning: "Placez le QR code du billet dans le cadre.",
      serial: "Billet n°",
      showCode: "Afficher le QR code",
      ticket: "Billet",
      ticketList: "Billets dans votre sac",
      unavailable: "Ce billet ne peut pas être contrôlé maintenant.",
      useCode: "Ouvrir le code",
      viewTicket: "Voir le billet",
    };
  }
  if (locale === "en") {
    return {
      alreadyRedeemed: "This ticket has already been checked in.",
      back: "Back",
      backToBag: "Back to tickets",
      checkIn: "Check in a ticket",
      confirm: "Confirm check-in",
      confirmHint:
        "Check the ticket number and holder first. This cannot be undone.",
      copy: "Copy link",
      copied: "Link copied",
      enterCode: "Paste ticket code or link",
      expired: "This code has expired. Ask the holder to refresh it.",
      generate: "Show check-in code",
      generatedHint: "Show this QR code to the organizer. It expires shortly.",
      holder: "Ticket holder",
      invalid: "This ticket code is invalid or cannot be found.",
      mismatch: "This ticket belongs to a different event.",
      myTicket: "My ticket",
      newTickets: "New tickets",
      noCamera: "Camera unavailable. Paste the ticket link below.",
      open: "Open ticket",
      pageTitle: "Ticket check-in",
      processing: "Checking in…",
      redeemed: "Ticket checked in",
      redeemedNoGift:
        "No tickets left to gift. Checked-in or previously gifted tickets cannot be transferred.",
      refresh: "Refresh code",
      scan: "Scan ticket",
      scanning: "Place the ticket QR code inside the frame.",
      serial: "Ticket #",
      showCode: "Show QR code",
      ticket: "Ticket",
      ticketList: "Tickets in your bag",
      unavailable: "This ticket cannot be checked in now.",
      useCode: "Open code",
      viewTicket: "View ticket",
    };
  }
  return {
    alreadyRedeemed: "这张票已经核销，不能再次入场。",
    back: "返回",
    backToBag: "返回票券列表",
    checkIn: "核销票券",
    confirm: "确认核销",
    confirmHint: "请先核对票号和持有人，确认后不可撤销。",
    copy: "复制核销链接",
    copied: "链接已复制",
    enterCode: "粘贴票券核销码或链接",
    expired: "此核销码已过期，请持票人刷新。",
    generate: "显示核销码",
    generatedHint: "向举办人出示此二维码，短时间后需刷新。",
    holder: "持票人",
    invalid: "此票券核销码无效或不存在。",
    mismatch: "这张票不属于当前活动，请核对票券。",
    myTicket: "我的票券",
    newTickets: "有新票券",
    noCamera: "无法使用相机，请在下方粘贴票券链接。",
    open: "查看票券",
    pageTitle: "票券核销",
    processing: "核销中…",
    redeemed: "核销成功",
    redeemedNoGift: "目前没有可赠送的票。已核销或赠送过的票不能再次赠送。",
    refresh: "刷新核销码",
    scan: "扫描票券二维码",
    scanning: "将持票人的票券二维码放入框内。",
    serial: "票号",
    showCode: "展示二维码",
    ticket: "票券",
    ticketList: "背包中的票券",
    unavailable: "这张票暂时无法核销。",
    useCode: "打开核销页面",
    viewTicket: "查看此票",
  };
}
