export function getTicketRedemptionCopy(locale: string) {
  if (locale === "fr") {
    return {
      alreadyRedeemed: "Ce billet a déjà été contrôlé.",
      back: "Retour",
      backToBag: "Retour aux billets",
      checkIn: "Contrôler un billet",
      checkedIn: "Déjà contrôlé",
      confirm: "Confirmer le contrôle",
      currentTicket: "Billet concerné",
      confirmHint:
        "Vérifiez le billet et son titulaire. Cette action est définitive.",
      codeLabel: "Code de contrôle à 6 chiffres",
      copy: "Copier le code",
      copied: "Code copié",
      enterCode: "Saisir le code à 6 chiffres",
      enterCodeHint: "Demandez le code au titulaire ou scannez son QR code.",
      enterCodeInvalid: "Saisissez le code de contrôle à 6 chiffres.",
      expired: "Ce code a expiré. Demandez un nouveau code au titulaire.",
      generate: "Afficher le code de contrôle",
      generatedHint:
        "Montrez le QR code ou donnez le code à l'organisateur. Valable 10 minutes.",
      giftLocked: "Ne peut plus être offert",
      holder: "Titulaire",
      holderCode: "Code Friemi du titulaire",
      holderCodeHint:
        "Les deux codes doivent appartenir au même titulaire et au même événement.",
      holderCodeInvalid: "Saisissez le code Friemi à 6 chiffres du titulaire.",
      invalid: "Ce code de billet est introuvable ou invalide.",
      mismatch: "Ce billet n'appartient pas à cet événement.",
      myTicket: "Mon billet",
      newTickets: "Nouveaux billets",
      noCamera:
        "La caméra est indisponible. Saisissez le code Friemi du titulaire et son code de contrôle ci-dessous.",
      open: "Ouvrir le billet",
      pageTitle: "Contrôle des billets",
      passTitle: "Présenter le billet",
      processing: "Contrôle en cours…",
      rateLimited:
        "Le code manuel est indisponible ou trop sollicité. Réessayez plus tard ou scannez le QR code.",
      redeemed: "Billet contrôlé",
      redeemedNoGift:
        "Aucun billet à offrir. Un billet contrôlé ou déjà offert ne peut plus être transféré.",
      refresh: "Actualiser le code",
      scan: "Scanner un billet",
      selectEvent:
        "Ouvrez le contrôle depuis le billet de l'événement concerné.",
      scanning: "Placez le QR code du billet dans le cadre.",
      showCode: "Afficher le QR code",
      ready: "Prêt pour le contrôle",
      ticket: "Billet",
      ticketList: "Billets dans votre sac",
      unavailable: "Ce billet ne peut pas être contrôlé maintenant.",
      useCode: "Vérifier le billet",
      viewTicket: "Voir le billet",
    };
  }
  if (locale === "en") {
    return {
      alreadyRedeemed: "This ticket has already been checked in.",
      back: "Back",
      backToBag: "Back to tickets",
      checkIn: "Check in a ticket",
      checkedIn: "Checked in",
      confirm: "Confirm check-in",
      currentTicket: "Current ticket",
      confirmHint: "Check the ticket and holder first. This cannot be undone.",
      codeLabel: "6-digit check-in code",
      copy: "Copy code",
      copied: "Code copied",
      enterCode: "Enter the 6-digit code",
      enterCodeHint: "Ask the holder for their code, or scan their QR code.",
      enterCodeInvalid: "Enter the 6-digit check-in code.",
      expired: "This code has expired. Ask the holder to refresh it.",
      generate: "Show check-in code",
      generatedHint:
        "Show the QR code or give the organizer your code. Valid for 10 minutes.",
      giftLocked: "Cannot be gifted again",
      holder: "Ticket holder",
      holderCode: "Holder's Friemi code",
      holderCodeHint: "Both codes must match the same holder and event.",
      holderCodeInvalid: "Enter the holder's 6-digit Friemi code.",
      invalid: "This ticket code is invalid or cannot be found.",
      mismatch: "This ticket belongs to a different event.",
      myTicket: "My ticket",
      newTickets: "New tickets",
      noCamera:
        "Camera unavailable. Enter the holder's Friemi code and check-in code below.",
      open: "Open ticket",
      pageTitle: "Ticket check-in",
      passTitle: "Present this ticket",
      processing: "Checking in…",
      rateLimited:
        "Manual code unavailable or used too often. Try again later or scan the QR code.",
      redeemed: "Ticket checked in",
      redeemedNoGift:
        "No tickets left to gift. Checked-in or previously gifted tickets cannot be transferred.",
      refresh: "Refresh code",
      scan: "Scan ticket",
      selectEvent: "Open check-in from the ticket for this event.",
      scanning: "Place the ticket QR code inside the frame.",
      showCode: "Show QR code",
      ready: "Ready for check-in",
      ticket: "Ticket",
      ticketList: "Tickets in your bag",
      unavailable: "This ticket cannot be checked in now.",
      useCode: "Check ticket",
      viewTicket: "View ticket",
    };
  }
  return {
    alreadyRedeemed: "这张票已经核销，不能再次入场。",
    back: "返回",
    backToBag: "返回票券列表",
    checkIn: "核销票券",
    checkedIn: "已核销",
    confirm: "确认核销",
    currentTicket: "当前票券",
    confirmHint: "请核对票券与持票人，确认后不可撤销。",
    codeLabel: "6 位核销码",
    copy: "复制核销码",
    copied: "核销码已复制",
    enterCode: "输入 6 位核销码",
    enterCodeHint: "向持票人询问核销码，也可以扫描票券二维码。",
    enterCodeInvalid: "请输入 6 位核销码。",
    expired: "此核销码已过期，请持票人刷新。",
    generate: "显示核销码",
    generatedHint: "向工作人员出示二维码或告知核销码，10 分钟内有效。",
    giftLocked: "不可转赠",
    holder: "持票人",
    holderCode: "持票人 Friemi 码",
    holderCodeHint: "人工核销需同时核对持票人和当前活动。",
    holderCodeInvalid: "请输入持票人的 6 位 Friemi 码。",
    invalid: "此票券核销码无效或不存在。",
    mismatch: "这张票不属于当前活动，请核对票券。",
    myTicket: "我的票券",
    newTickets: "有新票券",
    noCamera: "无法使用相机，请在下方输入持票人的 Friemi 码和核销码。",
    open: "查看票券",
    pageTitle: "票券核销",
    passTitle: "出示入场凭证",
    processing: "核销中…",
    rateLimited: "人工核销码暂不可用或尝试过多，请稍后重试或扫描二维码。",
    redeemed: "核销成功",
    redeemedNoGift: "目前没有可赠送的票。已核销或赠送过的票不能再次赠送。",
    refresh: "刷新核销码",
    scan: "扫描票券二维码",
    selectEvent: "请从对应活动票券的核销入口进入。",
    scanning: "将持票人的票券二维码放入框内。",
    showCode: "展示二维码",
    ready: "待核销",
    ticket: "票券",
    ticketList: "背包中的票券",
    unavailable: "这张票暂时无法核销。",
    useCode: "查验票券",
    viewTicket: "查看此票",
  };
}
