export function getTicketWorkbenchCopy(locale: string) {
  if (locale === "fr") {
    return {
      back: "Retour",
      title: "Espace de contrôle",
      chooseTicket: "Choisissez le billet à contrôler.",
      ticketCount: (count: number) =>
        `${count} ${count > 1 ? "billets autorisés" : "billet autorisé"}`,
      emptyTitle: "Aucun billet à contrôler",
      emptyHint:
        "Les billets apparaissent ici dès qu'un responsable ou un administrateur vous autorise. Vous n'avez pas besoin d'en posséder.",
      invitations: "Invitations en attente",
      invitedBy: (name: string) => `Invitation de ${name}`,
      invitedUnknown: "Invitation au contrôle",
      accept: "Accepter",
      decline: "Refuser",
      invitationPending: "Enregistrement…",
      invitationFailed: "Impossible de répondre à l'invitation. Réessayez.",
      ticketImage: (title: string) => `Image du billet ${title}`,
      independentAccess: "Autorisé à contrôler",
      scan: "Contrôler un billet",
      scanHint:
        "Scannez le QR code ou saisissez le code de contrôle à 6 caractères.",
      myHistory: "Mes contrôles",
      managerActions: "Gestion du billet",
      staff: "Personnel de contrôle",
      staffHint: "Inviter ou retirer l'accès au contrôle.",
      allHistory: "Tous les contrôles",
      allHistoryHint: "Consulter les entrées de ce billet.",
      pastTickets: "Contrôles précédents",
      pastHint:
        "Vous pouvez toujours consulter vos contrôles après la fin de l'autorisation.",
      historyHint: "Les billets que vous avez contrôlés pour cet événement.",
      historyTitle: "Mes contrôles",
      historyCount: (count: number) =>
        `${count} ${count > 1 ? "contrôles" : "contrôle"}`,
      historyEmpty: "Vous n'avez encore contrôlé aucun billet ici.",
      holder: "Titulaire",
      qr: "QR code",
      manual: "Code saisi",
      unknownMethod: "Contrôle",
      previous: "Précédent",
      next: "Suivant",
      page: (current: number, total: number) => `Page ${current} sur ${total}`,
      pagination: "Pages des contrôles",
      loading: "Chargement de l'espace de contrôle",
      loadFailed: "Impossible de charger les billets",
      loadFailedHint: "Réessayez dans un instant.",
      retry: "Réessayer",
    };
  }
  if (locale === "en") {
    return {
      back: "Back",
      title: "Check-in workspace",
      chooseTicket: "Choose the ticket you are checking in.",
      ticketCount: (count: number) =>
        `${count} ${count === 1 ? "ticket" : "tickets"} assigned`,
      emptyTitle: "No tickets to check in",
      emptyHint:
        "Tickets appear here after an organizer or administrator grants you access. You do not need to hold any tickets.",
      invitations: "Pending invitations",
      invitedBy: (name: string) => `Invited by ${name}`,
      invitedUnknown: "Check-in invitation",
      accept: "Accept",
      decline: "Decline",
      invitationPending: "Saving…",
      invitationFailed: "Could not update this invitation. Try again.",
      ticketImage: (title: string) => `${title} ticket image`,
      independentAccess: "Check-in access",
      scan: "Check in a ticket",
      scanHint: "Scan the QR code or enter the 6-character check-in code.",
      myHistory: "My check-ins",
      managerActions: "Ticket management",
      staff: "Check-in staff",
      staffHint: "Invite staff or remove access.",
      allHistory: "All check-ins",
      allHistoryHint: "Review every check-in for this ticket.",
      pastTickets: "Previous check-ins",
      pastHint: "You can still review your check-ins after access ends.",
      historyHint: "Tickets you checked in for this event.",
      historyTitle: "My check-ins",
      historyCount: (count: number) =>
        `${count} ${count === 1 ? "check-in" : "check-ins"}`,
      historyEmpty: "You have not checked in a ticket here yet.",
      holder: "Holder",
      qr: "QR scan",
      manual: "Manual code",
      unknownMethod: "Check-in",
      previous: "Previous",
      next: "Next",
      page: (current: number, total: number) => `Page ${current} of ${total}`,
      pagination: "Check-in history pages",
      loading: "Loading the check-in workspace",
      loadFailed: "Could not load tickets",
      loadFailedHint: "Try again in a moment.",
      retry: "Try again",
    };
  }
  return {
    back: "返回",
    title: "核销工作台",
    chooseTicket: "选择要核销的票券。",
    ticketCount: (count: number) => `可核销票种 ${count}`,
    emptyTitle: "暂无可核销票券",
    emptyHint: "店主或管理员授权后，票券会显示在这里。核销员无需持有票券。",
    invitations: "待处理邀请",
    invitedBy: (name: string) => `${name} 邀请你核销`,
    invitedUnknown: "核销邀请",
    accept: "接受",
    decline: "拒绝",
    invitationPending: "处理中…",
    invitationFailed: "暂时无法处理邀请，请重试。",
    ticketImage: (title: string) => `${title}票券图片`,
    independentAccess: "已获核销授权",
    scan: "核销票券",
    scanHint: "扫描二维码，或输入 6 位字母数字核销码。",
    myHistory: "我的核销记录",
    managerActions: "负责人操作",
    staff: "核销人员",
    staffHint: "邀请核销员或撤销权限。",
    allHistory: "全部核销记录",
    allHistoryHint: "查看这类票的逐笔核销。",
    pastTickets: "过往核销",
    pastHint: "核销权限结束后，你仍可查看自己的记录。",
    historyHint: "查看你在这个票种下核销过的票。",
    historyTitle: "我的核销记录",
    historyCount: (count: number) => `已核销 ${count} 张`,
    historyEmpty: "你还没有核销过这个票种。",
    holder: "持票人",
    qr: "扫码",
    manual: "手输码",
    unknownMethod: "核销",
    previous: "上一页",
    next: "下一页",
    page: (current: number, total: number) => `第 ${current} / ${total} 页`,
    pagination: "核销记录分页",
    loading: "正在加载核销工作台",
    loadFailed: "暂时无法加载票券",
    loadFailedHint: "请稍后重试。",
    retry: "重试",
  };
}
