export const brand = {
  appleIconPath: "/brand/v2_1/friemi-icon-apple-180.png",
  desktopBandImagePath: "/brand/v2_1/friemi-bg-desktop-soft-band.png",
  desktopWideImagePath: "/brand/v2_1/friemi-bg-desktop-wide.png",
  emptyStateIconPath: "/brand/v2_1/friemi-empty-state-mark.png",
  description:
    "Friemi helps overseas Chinese-speaking users discover activities, bring friends, and start plans nearby.",
  faviconPath: "/brand/v2_1/friemi-icon-pwa-192.png",
  legacyName: "Friemi",
  loadingImagePath: "/logo_loading_3d_counterclockwise_clean.svg",
  lockupHorizontalNavyPath: "/brand/v2_1/friemi-lockup-horizontal-navy.png",
  lockupHorizontalWhitePath: "/brand/v2_1/friemi-lockup-horizontal-white.png",
  logoIconPath: "/brand/v2_1/friemi-icon-transparent-512.png",
  logoPath: "/brand/v2_1/friemi-icon-square-1024.png",
  manifestIcon192Path: "/brand/v2_1/friemi-icon-pwa-192.png",
  manifestIcon512Path: "/brand/v2_1/friemi-icon-pwa-512.png",
  mobileFrameImagePath: "/brand/v2_1/friemi-bg-mobile-frame.png",
  name: "Friemi",
  shareImagePath: "/brand/v2_1/friemi-og-default-1200x630.png",
  shortDescription: "Find activities, bring friends, and start plans nearby.",
  title: "Friemi",
  titleImagePath: "/brand/v2_1/friemi-title-navy.png",
} as const;
