export function getMerchantBookingAdminCopy(locale: string) {
  if (locale === "fr")
    return {
      title: "Accès aux réservations",
      back: "Boutiques",
      detailBack: "Gestion de la boutique",
      entryHint: "Autoriser les boutiques à recevoir des réservations",
      description:
        "La boutique crée sa rencontre permanente et gère les demandes de ses clients.",
      granted: "Accès autorisé",
      denied: "Accès non autorisé",
      enabled: "Réservations ouvertes",
      paused: "Réservations en pause",
      unconfigured: "À configurer par la boutique",
      grant: "Autoriser les réservations",
      revoke: "Retirer l’accès",
      saving: "Enregistrement…",
      saved: "Accès mis à jour",
      revokeHint:
        "Le retrait bloque les nouvelles demandes. Les réservations existantes restent à traiter.",
      noOwner: "Attribuez d’abord un propriétaire à cette boutique.",
      bindOwner: "Attribuer un propriétaire",
      viewMeetup: "Voir la rencontre permanente",
      search: "Rechercher une boutique",
      submitSearch: "Rechercher",
      empty: "Aucune boutique trouvée.",
      previous: "Précédent",
      next: "Suivant",
      legacy: "Anciennes demandes de dates",
    };
  if (locale === "en")
    return {
      title: "Booking access",
      back: "Stores",
      detailBack: "Store management",
      entryHint: "Allow stores to receive reservations",
      description:
        "The store creates its permanent meetup and handles customer reservations.",
      granted: "Access granted",
      denied: "Access not granted",
      enabled: "Reservations open",
      paused: "Reservations paused",
      unconfigured: "Awaiting store setup",
      grant: "Grant booking access",
      revoke: "Revoke booking access",
      saving: "Saving…",
      saved: "Access updated",
      revokeHint:
        "Revoking access stops new requests. Existing reservations still need to be handled.",
      noOwner: "Assign an owner to this store first.",
      bindOwner: "Assign an owner",
      viewMeetup: "View permanent meetup",
      search: "Search stores",
      submitSearch: "Search",
      empty: "No stores found.",
      previous: "Previous",
      next: "Next",
      legacy: "Previous date requests",
    };
  return {
    title: "预约权限",
    back: "门店列表",
    detailBack: "门店管理",
    entryHint: "授权门店开通预约",
    description: "授权后，门店可创建长期聚吧并自行处理客户预约。",
    granted: "已授权",
    denied: "未授权",
    enabled: "正在接受预约",
    paused: "门店已暂停预约",
    unconfigured: "等待门店开启",
    grant: "授予预约权限",
    revoke: "关闭预约权限",
    saving: "保存中…",
    saved: "权限已更新",
    revokeHint: "关闭权限后停止接收新预约，已有预约仍由门店处理。",
    noOwner: "请先为门店绑定店主。",
    bindOwner: "绑定店主",
    viewMeetup: "查看长期聚吧",
    search: "搜索门店",
    submitSearch: "搜索",
    empty: "没有找到门店。",
    previous: "上一页",
    next: "下一页",
    legacy: "旧版日期申请记录",
  };
}
