const zh = {
  management: "预约管理",
  settings: "开放设置",
  createSpace: "创建长期聚吧",
  editSpace: "编辑长期聚吧",
  permanent: "长期聚吧",
  myBookings: "我的预约",
  details: "预约详情",
  back: "返回上一级",
  backStore: "返回门店管理",
  backBookings: "返回预约列表",
  backLobby: "返回聚吧",
  viewSpace: "查看长期聚吧",
  browse: "去看看聚吧",
  noAccess: "预约功能尚未开通",
  noAccessHint: "网站管理员开通后，你可以创建长期聚吧，持续接收用户预约。",
  setupTitle: "用一个长期聚吧接收预约",
  setupHint: "设置开放日期后，用户可在聚吧里选择日期和人数，你来确认每笔预约。",
  open: "接收预约中",
  paused: "已暂停新预约",
  pausedHint: "门店暂时不接受新预约。已有预约仍可在「我的预约」中查看。",
  accessPaused: "预约权限已暂停，已有预约仍可处理。",
  pending: "待处理",
  awaiting: "待确认",
  upcoming: "已接受",
  history: "历史记录",
  all: "全部",
  noPending: "暂时没有待处理预约",
  noUpcoming: "暂时没有已接受的预约",
  noHistory: "暂时没有历史记录",
  empty: "还没有预约",
  emptyHint: "在长期聚吧中选好日期，提交后等待门店确认。",
  legacy: "此前的日期报名",
  records: "预约记录",
  count: (n: number) => `${n} 笔`,
  people: (n: number) => `${n} 人`,
  publicCount: (n: number) => `已确认 ${n} 人`,
  submittedAt: "提交时间",
  reviewedAt: "处理时间",
  cancelledAt: "取消时间",
  title: "聚吧名称",
  description: "介绍",
  cover: "聚吧封面",
  identity: "聚吧内容",
  availability: "开放日期",
  daily: "每天",
  weekly: "每周",
  dates: "指定日期",
  weekdays: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
  startDate: "开始日期",
  endDate: "结束日期",
  noEnd: "留空表示长期开放",
  pickDates: "选择开放日期",
  addDate: "添加日期",
  removeDate: "移除日期",
  noDates: "还没有选择日期",
  closedDates: "临时不开放的日期",
  exceptionsHint: "这些日期不会接收新预约，已有预约保留。",
  enabled: "接收新预约",
  enabledHint: "暂停后，已有预约仍需正常处理。",
  save: "保存设置",
  create: "创建并开启预约",
  saving: "保存中…",
  saved: "设置已保存",
  savedHint: "用户可以从这个长期聚吧进入预约。",
  titlePlaceholder: "例如：周末一起吃饭",
  descriptionPlaceholder: "介绍门店，以及顾客预约前需要了解的事项。",
  optional: "选填",
  chooseDate: "选择日期",
  choosePeople: "预约人数",
  contact: "联系信息",
  contactName: "联系人",
  contactPhone: "联系电话",
  phoneHint: "必填，仅门店和你可见，用于确认预约。",
  note: "备注",
  notePlaceholder: "例如：有儿童同行、饮食要求",
  submit: "提交预约",
  submitting: "提交中…",
  submitted: "预约已提交",
  waitConfirmation: "等待门店确认，处理结果会通知你。",
  viewBooking: "查看预约",
  signIn: "登录后预约",
  ownerHint: "你正在查看顾客预约页面。",
  manage: "管理预约",
  acceptedNotice: "门店已接受预约，请按所选日期到店。",
  rejectedNotice: "门店未接受此次预约。你可以选择其他日期重新预约。",
  cancelledNotice: "此次预约已取消。",
  noOpenDates: "这个月暂无开放日期",
  previousMonth: "上个月",
  nextMonth: "下个月",
  calendar: "预约日历",
  selectedDate: "预约日期",
  acceptedPeople: "已确认人数",
  dateRequired: "请选择一个开放日期",
  changeBooking: "如需更改，请取消后重新预约。",
  cancel: "取消预约",
  cancelConfirm: "取消后会通知门店。",
  confirmCancel: "确认取消",
  cancelling: "取消中…",
  cancelled: "预约已取消",
  accept: "接受预约",
  reject: "拒绝预约",
  rejecting: "拒绝原因",
  rejectHint: "向顾客说明原因，方便重新安排。",
  confirmReject: "确认拒绝",
  processing: "处理中…",
  processed: "预约已处理",
  call: "联系顾客",
  telephone: "电话",
  customer: "预约人",
  rejectionReason: "未接受原因",
  status: {
    PENDING: "待门店确认",
    ACCEPTED: "已接受",
    REJECTED: "未接受",
    CANCELLED: "已取消",
  },
};

const en: typeof zh = {
  management: "Booking management",
  settings: "Availability",
  createSpace: "Create a permanent meetup",
  editSpace: "Edit permanent meetup",
  permanent: "Permanent meetup",
  myBookings: "My bookings",
  details: "Booking details",
  back: "Back",
  backStore: "Back to store",
  backBookings: "Back to bookings",
  backLobby: "Back to meetups",
  viewSpace: "View permanent meetup",
  browse: "Explore meetups",
  noAccess: "Bookings are not enabled yet",
  noAccessHint:
    "An administrator can enable bookings so you can create a permanent meetup and receive reservations.",
  setupTitle: "Receive bookings through one permanent meetup",
  setupHint:
    "Set your available dates. Guests choose a date and party size, and you confirm each booking.",
  open: "Accepting bookings",
  paused: "New bookings paused",
  pausedHint:
    "This store is not accepting new bookings. Existing reservations remain available in My bookings.",
  accessPaused:
    "Booking access is paused. You can still manage existing reservations.",
  pending: "To review",
  awaiting: "Pending",
  upcoming: "Accepted",
  history: "History",
  all: "All",
  noPending: "No bookings to review",
  noUpcoming: "No accepted bookings yet",
  noHistory: "No past bookings",
  empty: "No bookings yet",
  emptyHint:
    "Choose a date in a permanent meetup, then wait for the store to confirm.",
  legacy: "Previous date signups",
  records: "Bookings",
  count: (n: number) => `${n} booking${n === 1 ? "" : "s"}`,
  people: (n: number) => `${n} guest${n === 1 ? "" : "s"}`,
  publicCount: (n: number) => `${n} confirmed guest${n === 1 ? "" : "s"}`,
  submittedAt: "Submitted",
  reviewedAt: "Reviewed",
  cancelledAt: "Cancelled",
  title: "Meetup name",
  description: "Description",
  cover: "Meetup cover",
  identity: "Meetup details",
  availability: "Available dates",
  daily: "Every day",
  weekly: "Weekly",
  dates: "Specific dates",
  weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  startDate: "Start date",
  endDate: "End date",
  noEnd: "Leave empty for ongoing availability",
  pickDates: "Choose available dates",
  addDate: "Add date",
  removeDate: "Remove date",
  noDates: "No dates selected",
  closedDates: "Exceptional closing dates",
  exceptionsHint: "No new bookings on these dates. Existing bookings are kept.",
  enabled: "Accept new bookings",
  enabledHint: "Existing reservations still need attention when paused.",
  save: "Save settings",
  create: "Create and enable bookings",
  saving: "Saving…",
  saved: "Settings saved",
  savedHint: "Guests can book through this permanent meetup.",
  titlePlaceholder: "For example: Weekend meals together",
  descriptionPlaceholder:
    "Introduce the store and anything guests should know before booking.",
  optional: "optional",
  chooseDate: "Choose a date",
  choosePeople: "Party size",
  contact: "Contact details",
  contactName: "Contact name",
  contactPhone: "Phone number",
  phoneHint:
    "Required. Only you and the store can see it, to arrange your booking.",
  note: "Note",
  notePlaceholder: "For example: Children or dietary requirements",
  submit: "Request booking",
  submitting: "Submitting…",
  submitted: "Booking requested",
  waitConfirmation:
    "The store will review your request. You will be notified of its decision.",
  viewBooking: "View booking",
  signIn: "Sign in to book",
  ownerHint: "You are viewing the guest booking page.",
  manage: "Manage bookings",
  acceptedNotice:
    "The store has accepted your booking. Visit on the selected date.",
  rejectedNotice:
    "The store could not accept this booking. You can choose another date.",
  cancelledNotice: "This booking has been cancelled.",
  noOpenDates: "No available dates this month",
  previousMonth: "Previous month",
  nextMonth: "Next month",
  calendar: "Booking calendar",
  selectedDate: "Booking date",
  acceptedPeople: "Confirmed guests",
  dateRequired: "Choose an available date",
  changeBooking: "To make changes, cancel and submit a new booking.",
  cancel: "Cancel booking",
  cancelConfirm: "The store will be notified of your cancellation.",
  confirmCancel: "Confirm cancellation",
  cancelling: "Cancelling…",
  cancelled: "Booking cancelled",
  accept: "Accept booking",
  reject: "Decline booking",
  rejecting: "Reason for declining",
  rejectHint: "Let the guest know why, so they can make other plans.",
  confirmReject: "Confirm decline",
  processing: "Processing…",
  processed: "Booking updated",
  call: "Contact guest",
  telephone: "Phone",
  customer: "Guest",
  rejectionReason: "Reason",
  status: {
    PENDING: "Awaiting store confirmation",
    ACCEPTED: "Accepted",
    REJECTED: "Declined",
    CANCELLED: "Cancelled",
  },
};

const fr: typeof zh = {
  management: "Gestion des réservations",
  settings: "Disponibilités",
  createSpace: "Créer une sortie permanente",
  editSpace: "Modifier la sortie permanente",
  permanent: "Sortie permanente",
  myBookings: "Mes réservations",
  details: "Détail de la réservation",
  back: "Retour",
  backStore: "Retour à la boutique",
  backBookings: "Retour aux réservations",
  backLobby: "Retour aux sorties",
  viewSpace: "Voir la sortie permanente",
  browse: "Découvrir les sorties",
  noAccess: "Les réservations ne sont pas encore activées",
  noAccessHint:
    "Un administrateur peut activer la fonction pour vous permettre de créer une sortie permanente et de recevoir des réservations.",
  setupTitle: "Une sortie permanente pour vos réservations",
  setupHint:
    "Définissez vos jours d'ouverture. Les clients choisissent une date et un nombre de personnes ; vous confirmez chaque demande.",
  open: "Réservations ouvertes",
  paused: "Nouvelles réservations en pause",
  pausedHint:
    "La boutique ne reçoit pas de nouvelles réservations. Retrouvez vos demandes existantes dans Mes réservations.",
  accessPaused:
    "L'accès aux réservations est suspendu. Les demandes existantes restent accessibles.",
  pending: "À traiter",
  awaiting: "En attente",
  upcoming: "Acceptées",
  history: "Historique",
  all: "Toutes",
  noPending: "Aucune demande à traiter",
  noUpcoming: "Aucune réservation acceptée",
  noHistory: "Aucune réservation passée",
  empty: "Aucune réservation",
  emptyHint:
    "Choisissez une date dans une sortie permanente, puis attendez la confirmation de la boutique.",
  legacy: "Anciennes inscriptions par date",
  records: "Réservations",
  count: (n: number) => `${n} réservation${n > 1 ? "s" : ""}`,
  people: (n: number) => `${n} personne${n > 1 ? "s" : ""}`,
  publicCount: (n: number) =>
    `${n} personne${n > 1 ? "s" : ""} confirmée${n > 1 ? "s" : ""}`,
  submittedAt: "Demande envoyée",
  reviewedAt: "Traitée le",
  cancelledAt: "Annulée le",
  title: "Nom de la sortie",
  description: "Présentation",
  cover: "Image de la sortie",
  identity: "La sortie",
  availability: "Dates disponibles",
  daily: "Tous les jours",
  weekly: "Chaque semaine",
  dates: "Dates précises",
  weekdays: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
  startDate: "Date de début",
  endDate: "Date de fin",
  noEnd: "Laissez vide pour une ouverture permanente",
  pickDates: "Choisir les dates ouvertes",
  addDate: "Ajouter une date",
  removeDate: "Retirer la date",
  noDates: "Aucune date sélectionnée",
  closedDates: "Fermetures exceptionnelles",
  exceptionsHint:
    "Pas de nouvelles réservations à ces dates. Les demandes existantes sont conservées.",
  enabled: "Recevoir de nouvelles réservations",
  enabledHint:
    "Les réservations existantes restent à traiter pendant la pause.",
  save: "Enregistrer",
  create: "Créer et ouvrir les réservations",
  saving: "Enregistrement…",
  saved: "Paramètres enregistrés",
  savedHint: "Les clients peuvent réserver depuis cette sortie permanente.",
  titlePlaceholder: "Par exemple : Un repas ensemble le week-end",
  descriptionPlaceholder:
    "Présentez la boutique et les informations utiles avant de réserver.",
  optional: "facultatif",
  chooseDate: "Choisir une date",
  choosePeople: "Nombre de personnes",
  contact: "Coordonnées",
  contactName: "Nom du contact",
  contactPhone: "Téléphone",
  phoneHint:
    "Obligatoire. Visible uniquement par vous et la boutique pour confirmer la réservation.",
  note: "Remarque",
  notePlaceholder: "Par exemple : Enfants, besoins alimentaires",
  submit: "Demander une réservation",
  submitting: "Envoi…",
  submitted: "Demande envoyée",
  waitConfirmation:
    "La boutique va examiner votre demande. Vous recevrez une notification de sa décision.",
  viewBooking: "Voir la réservation",
  signIn: "Se connecter pour réserver",
  ownerHint: "Vous consultez la page de réservation des clients.",
  manage: "Gérer les réservations",
  acceptedNotice:
    "La boutique a accepté votre réservation. Rendez-vous à la date choisie.",
  rejectedNotice:
    "La boutique n'a pas pu accepter cette réservation. Vous pouvez choisir une autre date.",
  cancelledNotice: "Cette réservation a été annulée.",
  noOpenDates: "Aucune date disponible ce mois-ci",
  previousMonth: "Mois précédent",
  nextMonth: "Mois suivant",
  calendar: "Calendrier de réservation",
  selectedDate: "Date de réservation",
  acceptedPeople: "Personnes confirmées",
  dateRequired: "Choisissez une date disponible",
  changeBooking:
    "Pour modifier votre demande, annulez-la puis réservez à nouveau.",
  cancel: "Annuler la réservation",
  cancelConfirm: "La boutique sera informée de l'annulation.",
  confirmCancel: "Confirmer l'annulation",
  cancelling: "Annulation…",
  cancelled: "Réservation annulée",
  accept: "Accepter la réservation",
  reject: "Refuser la réservation",
  rejecting: "Motif du refus",
  rejectHint: "Expliquez le motif au client pour qu'il puisse s'organiser.",
  confirmReject: "Confirmer le refus",
  processing: "Traitement…",
  processed: "Réservation mise à jour",
  call: "Contacter le client",
  telephone: "Téléphone",
  customer: "Client",
  rejectionReason: "Motif",
  status: {
    PENDING: "En attente de confirmation",
    ACCEPTED: "Acceptée",
    REJECTED: "Refusée",
    CANCELLED: "Annulée",
  },
};

export function getBookingCopy(locale: string) {
  return locale === "fr" ? fr : locale === "en" ? en : zh;
}
