export function getAaCopy(locale: string) {
  if (locale === "fr") {
    return {
      title: "Dépenses partagées",
      back: "Retour au groupe",
      detailTab: "Opérations",
      settlementTab: "Règlement",
      add: "Ajouter",
      emptyTitle: "Aucune dépense pour le moment",
      emptyBody:
        "Ajoutez la première dépense quand le groupe commence à payer ensemble.",
      totalExpense: "Dépenses du groupe",
      entries: "opérations",
      youReceive: "Vous devez recevoir",
      youPay: "Vous devez payer",
      balanced: "Vous êtes à jour",
      noSettlement: "Tout le monde est à jour",
      noSettlementBody:
        "Aucun paiement n'est nécessaire avec les opérations validées.",
      recordPayment: "Enregistrer le paiement",
      pendingReview: "À valider",
      pendingConfirmation: "Confirmation requise",
      rejected: "Refusée",
      disputed: "Litige",
      voided: "Annulée",
      posted: "Validée",
      expense: "Dépense",
      income: "Revenu",
      transfer: "Paiement",
      freeze: "Geler",
      reopen: "Rouvrir",
      archive: "Archiver",
      settings: "Gestion du compte",
      freeNotice:
        "Gratuit signifie sans frais d'inscription. Ce compte répartit seulement les dépenses réelles du groupe.",
      readonly:
        "Le compte est en lecture seule. Les paiements et confirmations restent disponibles.",
      unavailable: "La répartition est momentanément indisponible.",
      forbidden: "Inscrivez-vous au groupe pour voir les dépenses partagées.",
      tooMany:
        "La répartition prend en charge jusqu'à 50 participants directs.",
      why: "Calculé à partir du solde net de toutes les opérations validées.",
      approve: "Valider",
      reject: "Refuser",
      confirm: "Confirmer",
      confirmPayment: "Confirmer le paiement",
      confirmReceipt: "Confirmer la réception",
      payerConfirmed: "Paiement effectué",
      payerPending: "Paiement à effectuer",
      payeeConfirmed: "Réception confirmée",
      payeePending: "Réception à confirmer",
      restore: "Restaurer",
      void: "Annuler",
      receipt: "justificatif",
      edit: "Modifier l'opération",
      saveChanges: "Enregistrer les modifications",
      conflict:
        "Une version plus récente existe. Vos modifications n'ont pas remplacé les données actuelles.",
      dismissConflict: "Conserver la version actuelle",
      dispute: "Signaler un litige",
      resolveDispute: "Valider l'opération",
      amount: "Montant",
      date: "Date",
      settlementBlocked:
        "Résolvez d'abord les validations, confirmations ou litiges en attente.",
      exportCsv: "Exporter en CSV",
    };
  }

  if (locale === "en") {
    return {
      title: "AA split",
      back: "Back to plan",
      detailTab: "Activity",
      settlementTab: "Settle up",
      add: "Add entry",
      emptyTitle: "No shared costs yet",
      emptyBody: "Add the first expense when the group starts paying together.",
      totalExpense: "Group expenses",
      entries: "entries",
      youReceive: "You should receive",
      youPay: "You need to pay",
      balanced: "You're all square",
      noSettlement: "Everyone is all square",
      noSettlementBody: "No payments are needed for the approved entries.",
      recordPayment: "Record payment",
      pendingReview: "Pending review",
      pendingConfirmation: "Confirmation needed",
      rejected: "Rejected",
      disputed: "Disputed",
      voided: "Voided",
      posted: "Posted",
      expense: "Expense",
      income: "Income",
      transfer: "Payment",
      freeze: "Freeze",
      reopen: "Reopen",
      archive: "Archive",
      settings: "Ledger controls",
      freeNotice:
        "Free means there is no signup fee. This ledger only splits real costs the group chooses to record.",
      readonly:
        "This ledger is read-only. Payments and confirmations remain available.",
      unavailable: "The split is temporarily unavailable.",
      forbidden: "Join this plan to see its shared costs.",
      tooMany: "AA split supports up to 50 direct participants.",
      why: "Calculated from everyone's net balance across all approved entries.",
      approve: "Approve",
      reject: "Reject",
      confirm: "Confirm",
      confirmPayment: "Confirm payment",
      confirmReceipt: "Confirm receipt",
      payerConfirmed: "Payment sent",
      payerPending: "Payment needed",
      payeeConfirmed: "Receipt confirmed",
      payeePending: "Confirm receipt",
      restore: "Restore",
      void: "Void",
      receipt: "receipt",
      edit: "Edit entry",
      saveChanges: "Save changes",
      conflict:
        "A newer version exists. Your edit did not overwrite the current data.",
      dismissConflict: "Keep current version",
      dispute: "Raise dispute",
      resolveDispute: "Keep entry posted",
      amount: "Amount",
      date: "Date",
      settlementBlocked:
        "Resolve pending reviews, confirmations, or disputes before settling up.",
      exportCsv: "Export CSV",
    };
  }

  return {
    title: "AA 核算",
    back: "返回聚吧",
    detailTab: "明细",
    settlementTab: "结算",
    add: "记一笔",
    emptyTitle: "还没有共同开支",
    emptyBody: "聚吧开始产生实际费用后，在这里记下第一笔。",
    totalExpense: "本次共同支出",
    entries: "笔记录",
    youReceive: "你应收",
    youPay: "你需支付",
    balanced: "你已结清",
    noSettlement: "大家都已结清",
    noSettlementBody: "按当前已入账记录，不需要再互相付款。",
    recordPayment: "记录付款",
    pendingReview: "待审核",
    pendingConfirmation: "待双方确认",
    rejected: "已驳回",
    disputed: "争议中",
    voided: "已作废",
    posted: "已入账",
    expense: "支出",
    income: "收入",
    transfer: "转账",
    freeze: "冻结核算",
    reopen: "重新开启",
    archive: "归档核算",
    settings: "核算管理",
    freeNotice:
      "“免费”只表示没有报名费；这里仅分摊参与者主动记录的实际共同开支。",
    readonly: "账本当前只读，仍可完成付款和双方确认。",
    unavailable: "核算暂时不可用，请稍后重试。",
    forbidden: "报名参加本聚吧后，才可以查看本次核算。",
    tooMany: "AA 核算最多支持 50 位直接费用参与者。",
    why: "根据所有已入账记录的全局净余额计算，因此不要求逐笔原路还款。",
    approve: "通过",
    reject: "驳回",
    confirm: "确认",
    confirmPayment: "确认已付款",
    confirmReceipt: "确认收款",
    payerConfirmed: "付款人已付款",
    payerPending: "等待付款人付款",
    payeeConfirmed: "收款方已确认",
    payeePending: "等待收款方确认",
    restore: "恢复",
    void: "作废",
    receipt: "张凭证",
    edit: "编辑记录",
    saveChanges: "保存修改",
    conflict: "这笔记录已有更新版本，你的修改没有覆盖当前数据。",
    dismissConflict: "保留当前版本",
    dispute: "发起争议",
    resolveDispute: "确认保留入账",
    amount: "金额",
    date: "日期",
    settlementBlocked: "请先处理待审核、待确认或争议记录，再按建议结算。",
    exportCsv: "导出 CSV",
  };
}

export function getAaStatusLabel(locale: string, status: string) {
  const copy = getAaCopy(locale);
  const labels: Record<string, string> = {
    PENDING_REVIEW: copy.pendingReview,
    PENDING_CONFIRMATION: copy.pendingConfirmation,
    REJECTED: copy.rejected,
    DISPUTED: copy.disputed,
    VOIDED: copy.voided,
    POSTED: copy.posted,
  };
  return labels[status] ?? status;
}
