export function getAdminResidencyCopy(locale: string) {
  if (locale === "fr")
    return {
      entry: "Demandes de réservation",
      entryHint: "Valider les dates proposées par les commerçants",
      title: "Réservations boutique",
      backMerchants: "Boutiques",
      backList: "Demandes de réservation",
      pending: "À valider",
      other: "Autres dates",
      emptyPending: "Aucune date en attente.",
      emptyOther: "Aucune autre date pour le moment.",
      requests: (count: number) =>
        `${count} demande${count > 1 ? "s" : ""} en attente`,
      signups: (count: number) => `${count} inscription${count > 1 ? "s" : ""}`,
      approve: "Valider la date",
      approving: "Validation…",
      reject: "Refuser la date",
      rejecting: "Refus…",
      reason: "Motif du refus",
      reasonHint:
        "Le commerçant verra ce motif et pourra proposer une nouvelle date.",
      reviewed: "La décision a été enregistrée.",
      failed: "Impossible d'enregistrer la décision.",
      cancel: "Annuler cette date validée",
      cancelPending: "Retirer cette demande",
      cancelHint:
        "La date disparaîtra du calendrier public. Les personnes inscrites seront prévenues.",
      cancelPendingHint:
        "Cette demande sera clôturée. Le commerçant pourra proposer une autre date.",
      cancelConfirm: "Confirmer l'annulation",
      cancelSuccess: "Date annulée.",
      cancelPublished: "Annuler la sortie et la réservation",
      cancelPublishedHint:
        "La sortie et la réservation seront annulées ensemble. Les participants recevront une notification.",
      cancelPublishedConfirm: "Annuler la sortie",
      status: {
        PENDING: "En attente",
        CONFIRMED: "Validée",
        REJECTED: "Refusée",
        CANCELLED: "Annulée",
        PUBLISHED: "Sortie créée",
      },
      publicPage: "Voir la boutique",
      activity: "Voir la sortie",
    };
  if (locale === "en")
    return {
      entry: "Store booking requests",
      entryHint: "Review dates proposed by merchants",
      title: "Store bookings",
      backMerchants: "Stores",
      backList: "Store booking requests",
      pending: "Needs review",
      other: "Other dates",
      emptyPending: "No dates need review.",
      emptyOther: "No other dates yet.",
      requests: (count: number) =>
        `${count} pending ${count === 1 ? "request" : "requests"}`,
      signups: (count: number) => `${count} signed up`,
      approve: "Confirm date",
      approving: "Confirming…",
      reject: "Reject date",
      rejecting: "Rejecting…",
      reason: "Reason for rejection",
      reasonHint: "The merchant will see this and can propose another date.",
      reviewed: "Decision saved.",
      failed: "Could not save the decision.",
      cancel: "Cancel this confirmed date",
      cancelPending: "Close this request",
      cancelHint:
        "The date will leave the public calendar. Signed-up people will be notified.",
      cancelPendingHint:
        "This request will be closed. The merchant can propose another date.",
      cancelConfirm: "Confirm cancellation",
      cancelSuccess: "Date cancelled.",
      cancelPublished: "Cancel meetup and booking",
      cancelPublishedHint:
        "The meetup and booking will be cancelled together. Participants will be notified.",
      cancelPublishedConfirm: "Cancel meetup",
      status: {
        PENDING: "Pending",
        CONFIRMED: "Confirmed",
        REJECTED: "Rejected",
        CANCELLED: "Cancelled",
        PUBLISHED: "Meetup created",
      },
      publicPage: "View store",
      activity: "View meetup",
    };
  return {
    entry: "店铺预约审核",
    entryHint: "审核各店铺开放的预约日期",
    title: "店铺预约审核",
    backMerchants: "店铺与物品",
    backList: "预约审核列表",
    pending: "待审核",
    other: "其他日期",
    emptyPending: "目前没有待审核的日期。",
    emptyOther: "还没有其他预约记录。",
    requests: (count: number) => `${count} 条待审核`,
    signups: (count: number) => `${count} 人已报名`,
    approve: "确认这个日期",
    approving: "确认中…",
    reject: "拒绝这个日期",
    rejecting: "提交中…",
    reason: "拒绝原因",
    reasonHint: "商家会看到原因，并可重新申请日期。",
    reviewed: "审核结果已保存。",
    failed: "保存失败，请重试。",
    cancel: "取消已确认日期",
    cancelPending: "关闭这条申请",
    cancelHint: "取消后将从公开日历撤下，并通知已报名用户。",
    cancelPendingHint: "这条申请将被关闭，商家可以重新申请日期。",
    cancelConfirm: "确认取消日期",
    cancelSuccess: "日期已取消。",
    cancelPublished: "取消聚吧与预约",
    cancelPublishedHint: "聚吧和预约会一并取消，并通知参与者。",
    cancelPublishedConfirm: "确认取消聚吧",
    status: {
      PENDING: "待审核",
      CONFIRMED: "已确认",
      REJECTED: "未通过",
      CANCELLED: "已取消",
      PUBLISHED: "已创建聚吧",
    },
    publicPage: "查看门店主页",
    activity: "查看聚吧",
  };
}
