export function getResidencyOwnerCopy(locale: string) {
  if (locale === "fr") {
    return {
      backStore: "Boutique",
      backProfile: "Mon profil",
      backReservations: "Réservations boutique",
      title: "Réservations boutique",
      requestHistory: "Ma demande de réservation",
      readOnlyRequest:
        "Cette demande reste consultable. Après la fermeture ou le changement de propriétaire de la boutique, vous ne pouvez plus la gérer.",
      expiredDate:
        "Cette date est passée. Il n'est plus possible de créer une sortie.",
      description:
        "Proposez une date. Elle sera ouverte aux inscriptions après validation.",
      requestDate: "Proposer une date",
      requestTitle: "Nouvelle date",
      date: "Date",
      eventTitle: "Titre public",
      eventDescription: "Présentation publique",
      dateHint:
        "Choisissez uniquement le jour. L'heure sera définie lors de la création de la sortie.",
      submit: "Envoyer pour validation",
      submitting: "Envoi…",
      submitted: "Date envoyée pour validation.",
      viewRequest: "Voir la demande",
      saveError:
        "Impossible d'envoyer cette date. Vérifiez les informations et réessayez.",
      status: {
        PENDING: "En attente",
        CONFIRMED: "Validée",
        REJECTED: "Refusée",
        CANCELLED: "Annulée",
        PUBLISHED: "Sortie créée",
      },
      signups: (count: number) =>
        `${count} personne${count > 1 ? "s" : ""} inscrite${count > 1 ? "s" : ""}`,
      signupList: "Personnes inscrites",
      originalSignupList: "Inscriptions avant la création de la sortie",
      noSignups: "Personne ne s'est encore inscrit pour cette date.",
      rejectedReason: "Motif du refus",
      reapply: "Proposer à nouveau cette date",
      createActivity: "Créer la sortie",
      viewActivity: "Voir la sortie",
      publishTitle: "Créer une sortie pour cette date",
      publishDescription:
        "Les personnes déjà inscrites rejoindront automatiquement la sortie.",
      startTime: "Heure de début",
      address: "Lieu de rendez-vous",
      addressHint: "Indiquez une adresse précise aux personnes inscrites.",
      startTimeHint: "La date reste celle déjà validée.",
      publish: "Créer la sortie",
      publishing: "Création…",
      publishSuccess:
        "La sortie est créée et les inscriptions ont été reprises.",
      publishError:
        "Impossible de créer la sortie. Vérifiez l'heure et réessayez.",
      cancel: "Annuler cette date",
      cancelConfirm: "Cette date ne sera plus ouverte aux inscriptions.",
      cancelSubmit: "Confirmer l'annulation",
      cancelling: "Annulation…",
      cancelSuccess: "Date annulée.",
      cancelError: "Impossible d'annuler cette date.",
      empty: "Aucune date proposée pour le moment.",
    };
  }

  if (locale === "en") {
    return {
      backStore: "Store",
      backProfile: "My profile",
      backReservations: "Store bookings",
      title: "Store bookings",
      requestHistory: "My booking request",
      readOnlyRequest:
        "You can still view this request. After the store closes or changes owners, you can no longer manage it.",
      expiredDate: "This date has passed. A meetup can no longer be created.",
      description:
        "Propose a date. People can sign up after an admin confirms it.",
      requestDate: "Propose a date",
      requestTitle: "New booking date",
      date: "Date",
      eventTitle: "Public title",
      eventDescription: "Public description",
      dateHint: "Choose a day only. Set the time when you create the meetup.",
      submit: "Send for review",
      submitting: "Sending…",
      submitted: "Date sent for review.",
      viewRequest: "View request",
      saveError: "Could not submit this date. Check the details and try again.",
      status: {
        PENDING: "Pending review",
        CONFIRMED: "Confirmed",
        REJECTED: "Rejected",
        CANCELLED: "Cancelled",
        PUBLISHED: "Meetup created",
      },
      signups: (count: number) => `${count} signed up`,
      signupList: "People signed up",
      originalSignupList: "Signups before the meetup was created",
      noSignups: "Nobody has signed up for this date yet.",
      rejectedReason: "Reason",
      reapply: "Propose this date again",
      createActivity: "Create meetup",
      viewActivity: "View meetup",
      publishTitle: "Create a meetup for this date",
      publishDescription:
        "People already signed up will join the meetup automatically.",
      startTime: "Start time",
      address: "Meeting address",
      addressHint: "Give people a precise place to meet.",
      startTimeHint: "The approved date stays the same.",
      publish: "Create meetup",
      publishing: "Creating…",
      publishSuccess: "Meetup created and signups transferred.",
      publishError:
        "Could not create the meetup. Check the time and try again.",
      cancel: "Cancel this date",
      cancelConfirm: "This date will close to new signups.",
      cancelSubmit: "Confirm cancellation",
      cancelling: "Cancelling…",
      cancelSuccess: "Date cancelled.",
      cancelError: "Could not cancel this date.",
      empty: "No booking dates have been proposed yet.",
    };
  }

  return {
    backStore: "门店管理",
    backProfile: "我的",
    backReservations: "店铺预约",
    title: "店铺预约",
    requestHistory: "我的预约申请",
    readOnlyRequest:
      "这条申请仍可查看；门店停用或更换店主后，原申请者不能继续管理。",
    expiredDate: "预约日期已过，不能再生成聚吧。",
    description: "开放店铺预约日期，管理员确认后用户即可报名。",
    requestDate: "申请预约日期",
    requestTitle: "申请新日期",
    date: "预约日期",
    eventTitle: "公开标题",
    eventDescription: "公开介绍",
    dateHint: "这里只选日期；创建聚吧时再确定开始时间。",
    submit: "提交审核",
    submitting: "提交中…",
    submitted: "已提交，等待管理员审核。",
    viewRequest: "查看申请",
    saveError: "提交失败，请检查内容后重试。",
    status: {
      PENDING: "待审核",
      CONFIRMED: "已确认",
      REJECTED: "未通过",
      CANCELLED: "已取消",
      PUBLISHED: "已创建聚吧",
    },
    signups: (count: number) => `${count} 人已报名`,
    signupList: "报名用户",
    originalSignupList: "生成聚吧前的预约用户",
    noSignups: "这个日期还没有人报名。",
    rejectedReason: "未通过原因",
    reapply: "重新申请这个日期",
    createActivity: "生成聚吧",
    viewActivity: "查看聚吧",
    publishTitle: "从预约生成聚吧",
    publishDescription: "已有报名用户会自动加入聚吧，无需再次报名。",
    startTime: "开始时间",
    address: "聚吧地点",
    addressHint: "填写参加者能找到的具体地址。",
    startTimeHint: "日期沿用管理员已确认的预约日期。",
    publish: "确认生成聚吧",
    publishing: "创建中…",
    publishSuccess: "聚吧已创建，报名用户已转入。",
    publishError: "创建失败，请检查时间后重试。",
    cancel: "取消这个日期",
    cancelConfirm: "取消后，这个日期将停止接受报名。",
    cancelSubmit: "确认取消",
    cancelling: "取消中…",
    cancelSuccess: "日期已取消。",
    cancelError: "取消失败，请重试。",
    empty: "还没有申请预约日期。",
  };
}
