export function getPollCopy(locale: string) {
  if (locale === "fr") {
    return {
      anonymous: "Invité anonyme",
      anonymousConfirm: "Voter anonymement",
      back: "Retour",
      cancelled: "Sondage annulé",
      close: "Clore le sondage",
      closed: "Clôturé",
      closesAt: "Clôture",
      copyLink: "Copier le lien",
      copySuccess: "Lien copié",
      create: "Créer un sondage",
      createAction: "Publier le sondage",
      description: "Description",
      descriptionPlaceholder: "Ajoutez un contexte utile (facultatif)",
      empty: "Aucun sondage pour le moment",
      emptyHint: "Créez une décision rapide pour ce groupe.",
      finalDecision: "Décision finale",
      guestLimit:
        "Le vote invité facilite la participation, mais ne garantit pas strictement une personne, une voix.",
      guestNickname: "Votre pseudo",
      guestNicknameOptional: "Votre pseudo (facultatif)",
      guestNicknamePlaceholder: "Ex. Camille",
      loginRequired: "Connectez-vous pour participer à ce sondage.",
      manage: "Gérer",
      memberRequired: "Ce sondage est réservé aux membres du groupe.",
      multiple: "Choix multiple",
      newOption: "Ajouter une option",
      noResults: "Les résultats ne sont pas encore visibles.",
      open: "En cours",
      option: "Option",
      people: "participants",
      poll: "Sondage",
      polls: "Sondages",
      question: "Question",
      questionPlaceholder: "Ex. Où allons-nous dîner ?",
      reopen: "Rouvrir",
      resultAfterClose: "Après la clôture",
      resultAfterVote: "Après mon vote",
      resultAlways: "Toujours visibles",
      resultOrganizerOnly: "Gestionnaires uniquement",
      resultVisibility: "Visibilité des résultats",
      selectAtLeastOne: "Sélectionnez au moins une option.",
      share: "Partager",
      shareAnyone: "Toute personne avec le lien",
      shareGenerate: "Générer un nouveau lien",
      shareHint: "Un nouveau lien invalide le précédent.",
      shareRevoke: "Désactiver le lien",
      shareRevokedSuccess: "Lien désactivé",
      shareLoggedIn: "Utilisateurs connectés avec le lien",
      shareMembers: "Membres du groupe uniquement",
      shareQr: "QR code",
      shareTitle: "Partager le sondage",
      single: "Choix unique",
      submit: "Envoyer mon vote",
      submitting: "Envoi...",
      totalVotes: "votes",
      update: "Modifier mon vote",
      voteSuccess: "Votre vote est enregistré.",
      voterCountsOnly: "Afficher uniquement les totaux",
      voterManagersOnly: "Identités visibles par les gestionnaires",
      voterParticipants: "Afficher les participants",
      voterVisibility: "Visibilité des votants",
      withdraw: "Retirer mon vote",
      nicknameRequired: "Pseudo obligatoire",
      nicknameOptional: "Pseudo facultatif, vote anonyme possible",
      options: "Options",
      maxSelections: "Nombre maximum de choix",
      deadlineOptional: "Date limite (facultative)",
      invalid: "Vérifiez les informations du sondage.",
      forbidden: "Vous n'avez pas l'autorisation d'effectuer cette action.",
      failed: "L'action a échoué. Réessayez.",
      tooManyRequests: "Trop de tentatives. Réessayez dans une minute.",
      shareRevoked: "Ce lien de sondage n'est plus valide.",
      anonymousLabel: "Anonyme",
      nicknameLabel: "Avec pseudo",
      participantsVisible: "Les noms sont visibles",
      countsOnly: "Résultats agrégés",
      endedActivity: "Ce groupe est terminé et ne peut plus créer de sondage.",
    };
  }

  if (locale === "en") {
    return {
      anonymous: "Anonymous guest",
      anonymousConfirm: "Vote anonymously",
      back: "Back",
      cancelled: "Poll cancelled",
      close: "Close poll",
      closed: "Closed",
      closesAt: "Closes",
      copyLink: "Copy link",
      copySuccess: "Link copied",
      create: "Create poll",
      createAction: "Publish poll",
      description: "Description",
      descriptionPlaceholder: "Add helpful context (optional)",
      empty: "No polls yet",
      emptyHint: "Create a quick decision for this group.",
      finalDecision: "Final decision",
      guestLimit:
        "Guest voting is convenient, but cannot strictly guarantee one real person per vote.",
      guestNickname: "Your nickname",
      guestNicknameOptional: "Your nickname (optional)",
      guestNicknamePlaceholder: "Example: Alex",
      loginRequired: "Sign in to take part in this poll.",
      manage: "Manage",
      memberRequired: "This poll is limited to group members.",
      multiple: "Multiple choice",
      newOption: "Add option",
      noResults: "Results are not visible yet.",
      open: "Open",
      option: "Option",
      people: "participants",
      poll: "Poll",
      polls: "Polls",
      question: "Question",
      questionPlaceholder: "Example: Where should we have dinner?",
      reopen: "Reopen",
      resultAfterClose: "After the poll closes",
      resultAfterVote: "After I vote",
      resultAlways: "Always visible",
      resultOrganizerOnly: "Managers only",
      resultVisibility: "Result visibility",
      selectAtLeastOne: "Select at least one option.",
      share: "Share",
      shareAnyone: "Anyone with the link",
      shareGenerate: "Generate a new link",
      shareHint: "Generating a new link invalidates the previous one.",
      shareRevoke: "Disable link",
      shareRevokedSuccess: "Link disabled",
      shareLoggedIn: "Signed-in users with the link",
      shareMembers: "Group members only",
      shareQr: "QR code",
      shareTitle: "Share poll",
      single: "Single choice",
      submit: "Submit vote",
      submitting: "Submitting...",
      totalVotes: "votes",
      update: "Update vote",
      voteSuccess: "Your vote has been saved.",
      voterCountsOnly: "Show totals only",
      voterManagersOnly: "Identities visible to managers",
      voterParticipants: "Show participants",
      voterVisibility: "Voter visibility",
      withdraw: "Withdraw my vote",
      nicknameRequired: "Nickname required",
      nicknameOptional: "Nickname optional; anonymous voting allowed",
      options: "Options",
      maxSelections: "Maximum selections",
      deadlineOptional: "Deadline (optional)",
      invalid: "Check the poll details and try again.",
      forbidden: "You do not have permission to do that.",
      failed: "The action failed. Try again.",
      tooManyRequests: "Too many attempts. Try again in one minute.",
      shareRevoked: "This poll link is no longer valid.",
      anonymousLabel: "Anonymous",
      nicknameLabel: "Named guest",
      participantsVisible: "Names are visible",
      countsOnly: "Aggregate results",
      endedActivity: "This group has ended and cannot create new polls.",
    };
  }

  return {
    anonymous: "匿名游客",
    anonymousConfirm: "匿名投票",
    back: "返回",
    cancelled: "投票已取消",
    close: "关闭投票",
    closed: "已关闭",
    closesAt: "截止时间",
    copyLink: "复制链接",
    copySuccess: "链接已复制",
    create: "创建投票",
    createAction: "发布投票",
    description: "补充说明",
    descriptionPlaceholder: "补充投票背景（选填）",
    empty: "还没有投票",
    emptyHint: "发起一个简单投票，让大家快速做决定。",
    finalDecision: "最终决定",
    guestLimit: "游客投票方便快速收集意见，但无法严格保证现实中的一人一票。",
    guestNickname: "你的昵称",
    guestNicknameOptional: "你的昵称（选填）",
    guestNicknamePlaceholder: "例如：小明",
    loginRequired: "登录后才能参与这个投票。",
    manage: "管理",
    memberRequired: "这个投票仅限聚吧成员参与。",
    multiple: "多选",
    newOption: "添加选项",
    noResults: "结果暂时不可见。",
    open: "进行中",
    option: "选项",
    people: "人参与",
    poll: "投票",
    polls: "投票",
    question: "投票问题",
    questionPlaceholder: "例如：这次聚餐去哪里？",
    reopen: "重新开放",
    resultAfterClose: "关闭后可见",
    resultAfterVote: "投票后可见",
    resultAlways: "始终可见",
    resultOrganizerOnly: "仅管理员可见",
    resultVisibility: "结果什么时候可见",
    selectAtLeastOne: "请至少选择一个选项。",
    share: "分享",
    shareAnyone: "任何持链接的人（允许游客）",
    shareGenerate: "生成新的分享链接",
    shareHint: "生成新链接后，之前的投票链接会立即失效。",
    shareRevoke: "停用分享链接",
    shareRevokedSuccess: "分享链接已停用",
    shareLoggedIn: "持链接的登录用户",
    shareMembers: "仅聚吧成员",
    shareQr: "二维码",
    shareTitle: "分享投票",
    single: "单选",
    submit: "提交投票",
    submitting: "提交中...",
    totalVotes: "票",
    update: "更新投票",
    voteSuccess: "投票已保存。",
    voterCountsOnly: "只显示票数",
    voterManagersOnly: "仅管理员查看投票人",
    voterParticipants: "参与者可查看投票人",
    voterVisibility: "谁可以看到投票人",
    withdraw: "撤销我的投票",
    nicknameRequired: "游客必须输入昵称",
    nicknameOptional: "昵称选填，留空可匿名",
    options: "投票选项",
    maxSelections: "最多可选",
    deadlineOptional: "截止时间（选填）",
    invalid: "请检查投票内容后再提交。",
    forbidden: "你没有权限执行这个操作。",
    failed: "操作失败，请稍后重试。",
    tooManyRequests: "操作过于频繁，请一分钟后再试。",
    shareRevoked: "这个投票链接已失效。",
    anonymousLabel: "匿名",
    nicknameLabel: "署名游客",
    participantsVisible: "显示投票人",
    countsOnly: "只看汇总",
    endedActivity: "聚吧已经结束，不能再创建投票。",
  };
}
